name: ox
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - alabaster=0.7.12=py_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.3.0=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py_0
  - beautifulsoup4=4.9.0=py38h32f6830_0
  - bleach=3.1.4=pyh9f0ad1d_0
  - blosc=1.18.1=h6538335_0
  - bokeh=2.0.1=py38h32f6830_0
  - boost-cpp=1.72.0=h0caebb8_0
  - bottleneck=1.3.2=py38h4b8e87e_1
  - branca=0.4.0=py_0
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cartopy=0.17.0=py38h3c826ef_1014
  - certifi=2020.4.5.1=py38h32f6830_0
  - cffi=1.14.0=py38ha419a9e_0
  - cfitsio=3.470=hfa6e2cd_2
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.1=pyh8c360ce_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cmarkgfm=0.4.2=py38hfa6e2cd_2
  - colorama=0.4.3=py_0
  - coverage=5.0.4=py38h9de7a3e_0
  - coveralls=2.0.0=py_0
  - cryptography=2.8=py38hb32ad35_1
  - curl=7.69.1=h1dcc11c_0
  - cycler=0.10.0=py_2
  - cython=0.29.16=py38hb99c5c2_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - deprecated=1.2.8=pyh9f0ad1d_0
  - descartes=1.1.0=py_4
  - dill=0.3.1.1=py38h32f6830_1
  - docopt=0.6.2=py_1
  - docutils=0.16=py38h32f6830_1
  - entrypoints=0.3=py38h32f6830_1001
  - expat=2.2.9=he025d50_2
  - fiona=1.8.13=py38hb7fdc2d_0
  - folium=0.10.1=py_0
  - freetype=2.10.1=ha9979f8_0
  - freexl=1.0.5=hd288d7e_1002
  - future=0.18.2=py38h32f6830_1
  - gdal=3.0.4=py38hf01e392_4
  - geographiclib=1.50=py_0
  - geopandas=0.7.0=py_1
  - geopy=1.21.0=py_0
  - geos=3.8.1=he025d50_0
  - geotiff=1.5.1=h3d29ae3_10
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.58.3=py38hfa79958_1004
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.5=nompi_ha405e13_1104
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.9=py_1
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.6.0=py38h32f6830_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2020.0=166
  - ipykernel=5.2.0=py38h5ca1d4c_1
  - ipython=7.13.0=py38h32f6830_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.16.0=py38h32f6830_1
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=hfa6e2cd_1001
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.2=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - jupyterlab=2.1.0=py_0
  - jupyterlab_server=1.1.0=py_1
  - kealib=1.4.13=hd6dc3df_0
  - keyring=21.1.1=py38h32f6830_2
  - kiwisolver=1.2.0=py38heaebd3c_0
  - krb5=1.17.1=hdd46e55_0
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1=default_hf44288c_0
  - libcurl=7.69.1=h1dcc11c_0
  - libffi=3.2.1=h6538335_1007
  - libgdal=3.0.4=hf258572_4
  - libiconv=1.15=hfa6e2cd_1006
  - libkml=1.3.0=h7e985d0_1011
  - liblapack=3.8.0=15_mkl
  - libnetcdf=4.7.4=nompi_hc957ea6_101
  - libpng=1.6.37=hfe6a214_1
  - libpq=12.2=hd9aa61d_1
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialindex=1.9.3=he025d50_3
  - libspatialite=4.3.0a=h51df0ed_1038
  - libssh2=1.8.2=h642c060_2
  - libtiff=4.1.0=h885aae3_6
  - libwebp=1.0.2=hfa6e2cd_5
  - libxml2=2.9.10=h9ce36c8_0
  - lz4-c=1.8.3=he025d50_1001
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - markupsafe=1.1.1=py38h9de7a3e_1
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py38h1626042_0
  - mistune=0.8.4=py38hfa6e2cd_1000
  - mkl=2020.0=166
  - mock=3.0.5=py38h32f6830_1
  - more-itertools=8.2.0=py_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - networkx=2.4=py_1
  - nodejs=13.12.0=0
  - notebook=6.0.3=py38_0
  - numexpr=2.7.1=py38hb99c5c2_1
  - numpy=1.18.1=py38ha749109_1
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1f=hfa6e2cd_0
  - osmnet=0.1.5=py_3
  - owslib=0.19.2=py_1
  - packaging=20.1=py_0
  - palettable=3.3.0=py_0
  - pandana=0.4.4=py38he350917_1
  - pandas=1.0.3=py38hbe40bda_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.2=py_0
  - patsy=0.5.1=py_0
  - pcre=8.44=h6538335_0
  - pickleshare=0.7.5=py38h32f6830_1001
  - pillow=7.1.1=py38h8103267_0
  - pip=20.0.2=py_2
  - pkginfo=1.5.0.1=py_0
  - pluggy=0.13.1=py38_0
  - poppler=0.67.0=h1707e21_8
  - poppler-data=0.4.9=1
  - postgresql=12.2=he14cc48_1
  - proj=7.0.0=hfe17d32_2
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - psycopg2=2.8.5=py38hecfd6bc_0
  - py=1.8.1=py_0
  - pycparser=2.20=py_0
  - pyepsg=0.4.0=py_0
  - pygments=2.6.1=py_0
  - pykdtree=1.3.1=py38h4b8e87e_1003
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.0=py38h1d58662_1
  - pyqt=5.12.3=py38h6538335_1
  - pyreadline=2.1=py38_1001
  - pyrsistent=0.16.0=py38h9de7a3e_0
  - pysal=2.1.0=py_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py38h32f6830_1
  - pytables=3.6.1=py38h26f9782_1
  - pytest=5.4.1=py38h32f6830_0
  - python=3.8.2=h5fd99cc_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pywin32=227=py38hfa6e2cd_0
  - pywin32-ctypes=0.2.0=py38h32f6830_1001
  - pywinpty=0.5.7=py38_0
  - pyyaml=5.3.1=py38h9de7a3e_0
  - pyzmq=19.0.0=py38hc5dc6fd_1
  - qt=5.12.5=h7ef1ec2_0
  - rasterio=1.1.3=py38h2617b1b_0
  - readme_renderer=24.0=py_0
  - requests=2.23.0=pyh8c360ce_2
  - requests-toolbelt=0.9.1=py_0
  - rtree=0.9.4=py38h7ad75cc_1
  - scikit-learn=0.22.2.post1=py38h7208079_0
  - scipy=1.3.2=py38h582fac2_0
  - seaborn=0.10.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=46.1.3=py38h32f6830_0
  - shapely=1.7.0=py38hbf43935_3
  - six=1.14.0=py_1
  - snowballstemmer=2.0.0=py_0
  - snuggs=1.4.7=py_0
  - soupsieve=1.9.4=py38h32f6830_1
  - sphinx=3.0.1=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.30.1=hfa6e2cd_0
  - statsmodels=0.11.1=py38h9de7a3e_1
  - tbb=2018.0.5=he980bc4_0
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - tiledb=1.7.0=hffbbd95_2
  - tk=8.6.10=hfa6e2cd_0
  - tornado=6.0.4=py38hfa6e2cd_0
  - tqdm=4.45.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py38h32f6830_1
  - twine=3.1.1=py38_0
  - typing_extensions=3.7.4.1=py38h32f6830_3
  - urbanaccess=0.2.0=py_1
  - urllib3=1.25.8=py38h32f6830_1
  - vc=14.1=h869be7e_1
  - vincent=0.4.4=py_1
  - vs2015_runtime=14.16.27012=h30e32a0_1
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_1003
  - winpty=0.4.3=4
  - wrapt=1.12.1=py38h9de7a3e_1
  - xerces-c=3.2.2=h6538335_1004
  - xlrd=1.2.0=py_0
  - xlwt=1.3.0=py_1
  - xz=5.2.5=h2fa13f4_0
  - yaml=0.2.2=hfa6e2cd_1
  - zeromq=4.3.2=h6538335_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=hd8a0e53_2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - python-igraph==0.7.1.post6
prefix: c:\Anaconda\envs\ox

