name: ox
channels:
  - conda-forge
dependencies:
  - access=1.1.8=pyhd8ed1ab_0
  - affine=2.4.0=pyhd8ed1ab_0
  - alabaster=0.7.13=pyhd8ed1ab_0
  - amply=0.1.5=pyhd8ed1ab_0
  - anyio=3.7.0=pyhd8ed1ab_1
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311ha68e1ae_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-lru=2.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - autopep8=2.0.2=pyhd8ed1ab_0
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - black=23.3.0=py311h1ea47a8_1
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.4=hdccc3a2_0
  - bokeh=3.1.1=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h9f4b32c_3
  - bottleneck=1.3.7=py311h59ca53f_0
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.5.7=h56e8100_0
  - cairo=1.16.0=hdecc03f_1016
  - cartopy=0.21.1=py311h178a126_1
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py311h7d9ee11_3
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cfitsio=4.2.0=h9ebe7e4_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=win_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contextily=1.3.0=pyhd8ed1ab_0
  - contourpy=1.0.7=py311h005e61a_0
  - coverage=7.2.7=py311ha68e1ae_0
  - curl=8.1.2=h68f0423_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.35=py311h12c1d0e_0
  - debugpy=1.6.7=py311h12c1d0e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - descartes=1.1.0=py_4
  - dill=0.3.6=pyhd8ed1ab_1
  - distlib=0.3.6=pyhd8ed1ab_0
  - docutils=0.19=py311h1ea47a8_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - esda=2.4.3=pyhd8ed1ab_0
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h63175ca_1
  - filelock=3.12.1=pyhd8ed1ab_0
  - fiona=1.9.4=py311h4e4dc46_0
  - flake8=6.0.0=pyhd8ed1ab_0
  - flake8-bugbear=23.6.5=pyhd8ed1ab_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.4=py311ha68e1ae_0
  - freetype=2.12.1=h546665d_1
  - freexl=1.0.6=h67ca5e6_1
  - furo=2023.5.20=pyhd8ed1ab_1
  - gdal=3.7.0=py311heaf1029_0
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.13.2=pyhd8ed1ab_1
  - geopandas-base=0.13.2=pyha770c72_1
  - geopy=2.3.0=pyhd8ed1ab_0
  - geos=3.11.2=h1537add_0
  - geotiff=1.7.1=h7222e44_8
  - gettext=0.21.1=h5728263_0
  - giddy=2.3.4=pyhd8ed1ab_0
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - glpk=5.0=h8ffe710_0
  - hdf4=4.2.15=h1334946_6
  - hdf5=1.14.0=nompi_h918d9b7_103
  - icu=72.1=h63175ca_0
  - identify=2.5.24=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - inequality=1.0.0=py_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.23.1=pyh025b116_0
  - ipython=8.14.0=pyh08f2357_0
  - ipywidgets=8.0.6=pyhd8ed1ab_0
  - isort=5.12.0=pyhd8ed1ab_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyh5bfe37b_1
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py311h1ea47a8_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.6.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.22.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.7=pyhd8ed1ab_1
  - kealib=1.5.1=hc8369a0_3
  - kiwisolver=1.4.4=py311h005e61a_1
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libaec=1.0.6=h63175ca_1
  - libarchive=3.6.2=h27c7867_0
  - libblas=3.9.0=17_win64_openblas
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=17_win64_openblas
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.18=hcfcfb64_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libflang=5.0.0=h6538335_20180525
  - libgdal=3.7.0=hdf18f8d_0
  - libglib=2.76.3=he8f3873_0
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - libkml=1.3.0=hf2ab4e4_1015
  - liblapack=3.9.0=17_win64_openblas
  - liblapacke=3.9.0=17_win64_openblas
  - libnetcdf=4.9.2=nompi_hc664c2b_104
  - libopenblas=0.3.23=pthreads_hc140b1d_0
  - libpng=1.6.39=h19919ed_0
  - libpq=15.3=ha9684e8_0
  - libpysal=4.7.0=pyhd8ed1ab_0
  - librttopo=1.1.0=he1da8c1_13
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=h50a8ebb_25
  - libsqlite=3.42.0=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libtiff=4.5.0=h6c8260b_6
  - libwebp-base=1.3.0=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.10.4=hc3477c8_0
  - libzip=1.9.2=h519de47_1
  - libzlib=1.2.13=hcfcfb64_4
  - llvm-meta=5.0.0=0
  - llvmlite=0.40.0=py311h5bc0dda_0
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=he774522_1000
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.3=py311ha68e1ae_0
  - matplotlib-base=3.7.1=py311h6e989c2_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - mgwr=2.1.2=py_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - momepy=0.6.0=pyhd8ed1ab_1
  - mpir=3.0.0=he025d50_1002
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - munch=3.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.4.0=pyhd8ed1ab_0
  - nbdime=3.2.1=pyhd8ed1ab_0
  - nbformat=5.9.0=pyhd8ed1ab_0
  - nbqa=1.7.0=pyhd8ed1ab_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - nodeenv=1.8.0=pyhd8ed1ab_0
  - nodejs=18.15.0=h57928b3_1
  - nomkl=1.0=h5ca1d4c_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numba=0.57.0=py311h2c0921f_1
  - numexpr=2.8.4=py311h0aebda5_100
  - numpy=1.24.3=py311h0b4df5a_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openmp=5.0.0=vc14_1
  - openssl=3.1.1=hcfcfb64_1
  - overrides=7.3.1=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.2=py311hf63dbb6_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.11.1=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py311hde623f7_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.3=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - pointpats=2.3.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.05.0=h45d20d0_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.3=hd87cd2b_0
  - pre-commit=3.3.2=pyha770c72_0
  - proj=9.2.0=heca977f_0
  - prometheus_client=0.17.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.5=py311ha68e1ae_0
  - psycopg2=2.9.3=py311hb12f294_2
  - pthread-stubs=0.4=hcd874cb_1001
  - pulp=2.7.0=py311h1ea47a8_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyflakes=3.0.1=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.5.0=py311h095e9de_1
  - pyrsistent=0.19.3=py311ha68e1ae_0
  - pysal=23.1=pyhd8ed1ab_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - pytest=7.3.1=pyhd8ed1ab_0
  - python=3.11.4=h2628c8c_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-igraph=0.10.4=py311h8db4363_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pywin32=304=py311h12c1d0e_2
  - pywinpty=2.0.10=py311h12c1d0e_0
  - pyyaml=6.0=py311ha68e1ae_5
  - pyzmq=25.1.0=py311h7b3f143_0
  - quantecon=0.5.3=pyhd8ed1ab_0
  - rasterio=1.3.7=py311h826718d_1
  - rasterstats=0.19.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rtree=1.0.1=py311hcacb13a_1
  - scikit-learn=1.2.2=py311h142b183_2
  - scipy=1.10.1=py311h37ff6ca_3
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - segregation=2.4.2=pyhd8ed1ab_0
  - send2trash=1.8.2=pyh08f2357_0
  - setuptools=67.7.2=pyhd8ed1ab_0
  - shapely=2.0.1=py311h343093d_1
  - simplejson=3.19.1=py311ha68e1ae_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=hfb803bf_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - spaghetti=1.7.3=pyhd8ed1ab_0
  - spglm=1.0.8=py_0
  - sphinx=6.2.1=pyhd8ed1ab_0
  - sphinx-basic-ng=1.0.0b1=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - spint=1.0.7=pyhd8ed1ab_0
  - splot=1.1.5.post1=pyhd8ed1ab_0
  - spopt=0.5.0=pyhd8ed1ab_0
  - spreg=1.3.2=pyhd8ed1ab_0
  - spvcm=0.3.0=py_0
  - sqlite=3.42.0=hcfcfb64_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py311h59ca53f_1
  - suitesparse=5.4.0=h5d0cbe0_1
  - sympy=1.12=pyh04b8f61_3
  - terminado=0.17.0=pyh08f2357_0
  - texttable=1.6.7=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.13.2=h3132609_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - tobler=0.10=pyhd8ed1ab_0
  - tokenize-rt=5.0.0=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.2=py311ha68e1ae_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.6.3=hd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - ukkonen=1.0.1=py311h005e61a_3
  - urllib3=2.0.3=pyhd8ed1ab_0
  - vc=14.3=hb25d44b_16
  - vc14_runtime=14.34.31931=h5081d32_16
  - virtualenv=20.23.0=pyhd8ed1ab_0
  - vs2015_runtime=14.34.31931=hed1258a_16
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.3=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.7=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - xerces-c=3.2.4=h63175ca_2
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2023.5.0=pyhd8ed1ab_1
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_4
  - zstd=1.5.2=h12be248_6
prefix: C:\Users\Geoff\mambaforge\envs\ox
