name: ox
channels:
  - conda-forge
dependencies:
  - access=1.1.8=pyhd8ed1ab_1
  - affine=2.4.0=pyhd8ed1ab_0
  - alabaster=0.7.16=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - archspec=0.2.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312he70551f_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - autopep8=2.1.0=pyhd8ed1ab_0
  - aws-c-auth=0.7.18=hba7c1ab_0
  - aws-c-cal=0.6.11=ha21e00f_0
  - aws-c-common=0.9.15=hcfcfb64_0
  - aws-c-compression=0.2.18=ha21e00f_3
  - aws-c-event-stream=0.4.2=hf668b60_8
  - aws-c-http=0.8.1=hd704247_10
  - aws-c-io=0.14.7=h14865c8_6
  - aws-c-mqtt=0.10.4=h748201e_0
  - aws-c-s3=0.5.7=h0ac6cc1_2
  - aws-c-sdkutils=0.1.15=ha21e00f_3
  - aws-checksums=0.1.18=ha21e00f_3
  - aws-crt-cpp=0.26.8=h2199128_2
  - aws-sdk-cpp=1.11.267=h3f4ca61_7
  - azure-core-cpp=1.11.1=h249a519_1
  - azure-identity-cpp=1.6.0=h91493d7_1
  - azure-storage-blobs-cpp=12.10.0=h91493d7_1
  - azure-storage-common-cpp=12.5.0=h91493d7_4
  - babel=2.14.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.strenum=1.2.8=pyhd8ed1ab_0
  - backports.tarfile=1.0.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.8.1=pyhd8ed1ab_0
  - blosc=1.21.5=hbd69f2e_1
  - boltons=24.0.0=pyhd8ed1ab_0
  - boolean.py=4.0=pyhd8ed1ab_0
  - bottleneck=1.3.8=py312ha90f08f_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.1.0=py312h53d5487_1
  - bzip2=1.0.8=hcfcfb64_5
  - c-ares=1.28.1=hcfcfb64_0
  - ca-certificates=2024.2.2=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h1fef639_0
  - cartopy=0.23.0=py312h2ab9e98_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py312he70551f_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cfitsio=4.4.0=h9b0cee5_1
  - chardet=5.2.0=py312h2e8e312_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cirun=0.30=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cmarkgfm=0.8.0=py312he70551f_3
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=24.3.0=py312h2e8e312_0
  - conda-build=24.3.0=py312h2e8e312_1
  - conda-forge-pinning=2024.05.02.11.25.06=hd8ed1ab_0
  - conda-index=0.4.0=pyhd8ed1ab_0
  - conda-libmamba-solver=24.1.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - conda-smithy=3.35.0=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h0d7def4_0
  - coverage=7.5.0=py312h4389bb4_0
  - cryptography=42.0.5=py312h1f4a190_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py312h53d5487_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - descartes=1.1.0=py_4
  - distlib=0.3.8=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_0
  - editables=0.5=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - esda=2.5.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h63175ca_0
  - filelock=3.14.0=pyhd8ed1ab_0
  - fmt=10.2.1=h181d51b_0
  - folium=0.16.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py312he70551f_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hdaf720e_2
  - freexl=2.0.0=h8276f4a_0
  - furo=2024.4.27=pyhd8ed1ab_0
  - gdal=3.8.5=py312hea5013e_2
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geos=3.12.1=h1537add_0
  - geotiff=1.7.1=hed9d743_16
  - giddy=2.3.5=pyhd8ed1ab_0
  - git=2.45.0=h57928b3_1
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glpk=5.0=h8ffe710_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hatch=1.10.0=pyhd8ed1ab_0
  - hatchling=1.24.2=pyhd8ed1ab_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.3=nompi_h73e8ff5_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - hyperlink=21.0.0=pyhd3deb0d_0
  - icu=73.2=h63175ca_0
  - identify=2.5.36=pyhd8ed1ab_0
  - idna=3.7=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - inequality=1.0.1=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipython=8.22.2=pyh7428d3b_0
  - ipywidgets=8.1.2=pyhd8ed1ab_0
  - isodate=0.6.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_1
  - jaraco.context=5.3.0=pyhd8ed1ab_1
  - jaraco.functools=4.0.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py312h2e8e312_3
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyh5bfe37b_1
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h2e8e312_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - kealib=1.5.3=hd248416_0
  - keyring=25.2.0=pyh7428d3b_0
  - kiwisolver=1.4.5=py312h0d7def4_1
  - krb5=1.21.2=heb0366b_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240116.2=cxx17_h63175ca_0
  - libaec=1.1.3=h63175ca_0
  - libarchive=3.7.2=h313118b_1
  - libblas=3.9.0=22_win64_openblas
  - libboost-headers=1.84.0=h57928b3_2
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=22_win64_openblas
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.7.1=hd5e4a3a_0
  - libdeflate=1.20=hcfcfb64_0
  - libexpat=2.6.2=h63175ca_0
  - libffi=3.4.2=h8ffe710_5
  - libflang=5.0.0=h6538335_20180525
  - libgdal=3.8.5=hfb9f81c_2
  - libglib=2.80.0=h39d0aa6_6
  - libgoogle-cloud=2.23.0=h68df31e_1
  - libgoogle-cloud-storage=2.23.0=hb581fae_1
  - libgrpc=1.62.2=h5273850_0
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - libkml=1.3.0=haf3e7a6_1018
  - liblapack=3.9.0=22_win64_openblas
  - liblief=0.14.1=he0c23c2_1
  - libmamba=1.5.8=h3f09ed1_0
  - libmambapy=1.5.8=py312h66cf91f_0
  - libnetcdf=4.9.2=nompi_h07c049d_113
  - libopenblas=0.3.27=pthreads_hc140b1d_0
  - libpng=1.6.43=h19919ed_0
  - libpq=16.2=hdb24f17_1
  - libprotobuf=4.25.3=h503648d_0
  - libpysal=4.10=pyhd8ed1ab_0
  - libre2-11=2023.09.01=hf8d8778_2
  - librttopo=1.1.0=h94c4f80_15
  - libsodium=1.0.18=h8d14728_1
  - libsolv=0.7.29=h0ea2cb4_0
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.1.0=hf13de1f_5
  - libsqlite=3.45.3=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libtiff=4.6.0=hddb2be6_3
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.12.6=hc3477c8_2
  - libxslt=1.1.39=h3df6e99_0
  - libzip=1.10.1=h1d365fa_3
  - libzlib=1.2.13=hcfcfb64_5
  - license-expression=30.1.1=pyhd8ed1ab_0
  - llvm-meta=5.0.0=0
  - llvmlite=0.42.0=py312h7894644_1
  - lxml=5.2.1=py312h56c7e3b_0
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=hcfcfb64_1001
  - m2-msys2-runtime=2.5.0.17080.65c939c=3
  - m2-patch=2.7.5=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312he70551f_0
  - matplotlib-base=3.8.4=py312h26ecaf7_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - menuinst=2.0.2=py312h53d5487_0
  - mgwr=2.2.1=pyhd8ed1ab_0
  - minizip=4.0.5=h5bed578_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - momepy=0.7.0=pyhd8ed1ab_0
  - more-itertools=10.2.0=pyhd8ed1ab_0
  - mpir=3.0.0=he025d50_1002
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msrest=0.6.21=pyh44b312d_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=1.10.0=py312h4389bb4_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_0
  - nbdime=4.0.1=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nbqa=1.8.5=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - nh3=0.2.17=py312h426fad5_0
  - nodeenv=1.8.0=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.59.1=py312h115d327_0
  - numexpr=2.9.0=py312h8d8c32f_100
  - numpy=1.26.4=py312h8753938_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.2=h3d672ee_0
  - openmp=5.0.0=vc14_1
  - openssl=3.3.0=hcfcfb64_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py312h2ab9e98_0
  - pandas-stubs=2.2.1.240316=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=h17e33f8_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py312h6f6a607_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.4=h63175ca_0
  - pkginfo=1.10.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pointpats=2.4.0=pyhd8ed1ab_0
  - poppler=24.04.0=h747fd5a_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.2=h94c9ec1_1
  - pre-commit=3.7.0=pyha770c72_0
  - proj=9.4.0=he13c7e8_1
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py312he70551f_0
  - pthread-stubs=0.4=hcd874cb_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.8.0=py312h2e8e312_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-lief=0.14.1=py312h275cf98_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycodestyle=2.11.1=pyhd8ed1ab_0
  - pycosat=0.6.6=py312he70551f_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pycryptodome=3.20.0=py312he70551f_0
  - pygithub=2.3.0=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py312hc560f31_3
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyproj=3.6.1=py312h616b599_6
  - pysal=23.7=pyhd8ed1ab_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - pytest=8.2.0=pyhd8ed1ab_0
  - pytest-cov=5.0.0=pyhd8ed1ab_0
  - python=3.12.3=h2628c8c_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-igraph=0.11.4=py312hd474c18_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-libarchive-c=5.1=py312h2e8e312_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=306=py312h53d5487_2
  - pywin32-ctypes=0.2.2=py312h2e8e312_1
  - pywinpty=2.0.13=py312h53d5487_0
  - pyyaml=6.0.1=py312he70551f_1
  - pyzmq=26.0.2=py312hd7027bb_0
  - quantecon=0.7.2=pyhd8ed1ab_0
  - rasterio=1.3.10=py312h7f7071e_0
  - rasterstats=0.19.0=pyhd8ed1ab_0
  - re2=2023.09.01=hd3b24a8_2
  - readme_renderer=42.0=pyhd8ed1ab_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - reproc=14.2.4.post0=hcfcfb64_1
  - reproc-cpp=14.2.4.post0=h63175ca_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986=2.0.0=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.7.1=pyhd8ed1ab_0
  - ripgrep=14.1.0=h7f3b576_0
  - rpds-py=0.18.0=py312hfccd98a_0
  - rtree=1.2.0=py312h72b5f30_0
  - ruamel.yaml=0.18.6=py312he70551f_0
  - ruamel.yaml.clib=0.2.8=py312he70551f_0
  - ruff=0.4.2=py312h7a6832a_0
  - scikit-learn=1.4.2=py312hcacafb1_0
  - scipy=1.13.0=py312h8753938_0
  - scrypt=0.8.24=py312h6be9b4e_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - segregation=2.5=pyhd8ed1ab_1
  - send2trash=1.8.3=pyh5737063_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - shapely=2.0.4=py312h7d70906_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - simplejson=3.19.2=py312he70551f_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.0=hfb803bf_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - spaghetti=1.7.5.post1=pyhd8ed1ab_0
  - spdlog=1.13.0=h64d2f7d_0
  - spglm=1.1.0=pyhd8ed1ab_1
  - sphinx=7.3.7=pyhd8ed1ab_0
  - sphinx-autodoc-typehints=2.1.0=pyhd8ed1ab_0
  - sphinx-basic-ng=1.0.0b2=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=1.0.8=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.5=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - spint=1.0.7=pyhd8ed1ab_1
  - splot=1.1.5.post1=pyhd8ed1ab_0
  - spopt=0.6.0=pyhd8ed1ab_0
  - spreg=1.4.2=pyhd8ed1ab_0
  - spvcm=0.3.0=pyhd8ed1ab_1
  - sqlite=3.45.3=hcfcfb64_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py312ha90f08f_0
  - sympy=1.12=pyh04b8f61_3
  - terminado=0.18.1=pyh5737063_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiledb=2.22.0=h5657395_3
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tobler=0.11.2=pyhd8ed1ab_2
  - tokenize-rt=5.2.0=pyhd8ed1ab_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomli-w=1.0.0=pyhd8ed1ab_0
  - tomlkit=0.12.4=pyha770c72_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py312he70551f_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trove-classifiers=2024.4.10=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - twine=5.0.0=pyhd8ed1ab_0
  - typeguard=4.2.1=pyhd8ed1ab_0
  - typer=0.12.3=pyhd8ed1ab_0
  - typer-slim=0.12.3=pyhd8ed1ab_0
  - typer-slim-standard=0.12.3=hd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - types-pytz=2024.1.0.20240417=pyhd8ed1ab_0
  - types-requests=2.31.0.20240406=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - ukkonen=1.0.1=py312h0d7def4_4
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.7=h1537add_1
  - urllib3=2.2.1=pyhd8ed1ab_0
  - userpath=1.7.0=pyhd8ed1ab_0
  - uv=0.1.39=ha08ef0e_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - virtualenv=20.26.1=pyhd8ed1ab_0
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - vsts-python-api=0.1.25=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - wrapt=1.16.0=py312he70551f_0
  - xerces-c=3.2.5=h63175ca_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2024.4.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yaml-cpp=0.8.0=h63175ca_0
  - zeromq=4.3.5=he0c23c2_3
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zstandard=0.22.0=py312h01d794b_0
  - zstd=1.5.5=h12be248_0
  - pip:
      - fiona==1.9.6
      - osmnx==2.0.0b0
prefix: C:\Users\Geoff\miniforge3\envs\ox
