name: ox
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - altair=3.1.0=py37_0
  - asn1crypto=0.24.0=py37_1003
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py_0
  - beautifulsoup4=4.7.1=py37_1001
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - bokeh=1.2.0=py37_0
  - boost-cpp=1.70.0=h6a4c333_0
  - bottleneck=1.2.1=py37h452e1ab_1001
  - branca=0.3.1=py_0
  - bzip2=1.0.6=hfa6e2cd_1002
  - ca-certificates=2019.6.16=hecc5488_0
  - cartopy=0.17.0=py37h814cdbc_1004
  - certifi=2019.6.16=py37_0
  - cffi=1.12.3=py37hb32ad35_0
  - cfitsio=3.430=hfa6e2cd_1002
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cmarkgfm=0.4.2=py37hfa6e2cd_2
  - colorama=0.4.1=py_0
  - coverage=4.5.3=py37hfa6e2cd_0
  - coveralls=1.8.1=py_0
  - cryptography=2.7=py37hb32ad35_0
  - curl=7.65.1=h4496350_0
  - cycler=0.10.0=py_1
  - cython=0.29.10=py37h6538335_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - descartes=1.1.0=py_3
  - docopt=0.6.2=py_1
  - docutils=0.14=py37_1001
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=habb2df7_1003
  - fiona=1.8.6=py37hce0be61_3
  - folium=0.9.1=py_0
  - freetype=2.10.0=h5db478b_0
  - freexl=1.0.5=hd288d7e_1002
  - future=0.17.1=py37_1000
  - gdal=2.4.1=py37he6b6c38_5
  - geographiclib=1.49=py_0
  - geopandas=0.5.0=py_2
  - geopy=1.20.0=py_0
  - geos=3.7.1=he025d50_1000
  - geotiff=1.4.3=h8408f58_1000
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.58.3=hc0c2ac7_1001
  - hdf4=4.2.13=hf8e6fe8_1002
  - hdf5=1.10.5=nompi_hcc15c50_1100
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.1=vc14_0
  - idna=2.8=py37_1000
  - imagesize=1.1.0=py_0
  - importlib_metadata=0.18=py37_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipyleaflet=0.10.5=py37_0
  - ipython=7.5.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.14.0=py37_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=hfa6e2cd_1001
  - jsonschema=3.0.1=py37_0
  - jupyter_client=5.2.4=py_3
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.35.6=py37_0
  - jupyterlab_server=0.2.0=py_0
  - kealib=1.4.10=hf7dc31f_1005
  - kiwisolver=1.1.0=py37he980bc4_0
  - krb5=1.16.3=hdd46e55_1001
  - libblas=3.8.0=8_mkl
  - libcblas=3.8.0=8_mkl
  - libcurl=7.65.1=h4496350_0
  - libffi=3.2.1=h6538335_1006
  - libgdal=2.4.1=h6b3497b_5
  - libiconv=1.15=hfa6e2cd_1005
  - libkml=1.3.0=h4ece8bf_1010
  - liblapack=3.8.0=8_mkl
  - libnetcdf=4.6.2=ha953453_1002
  - libpng=1.6.37=h7602738_0
  - libpq=11.3=hb0bdaea_0
  - libsodium=1.0.16=h2fa13f4_1001
  - libspatialindex=1.8.5=he025d50_4
  - libspatialite=4.3.0a=h6a0152f_1026
  - libssh2=1.8.2=h642c060_2
  - libtiff=4.0.10=h6512ee2_1003
  - libxml2=2.9.9=h9ce36c8_0
  - lz4-c=1.8.3=he025d50_1001
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - mapclassify=2.0.1=py_0
  - markupsafe=1.1.1=py37hfa6e2cd_0
  - matplotlib=3.1.0=py37_1
  - matplotlib-base=3.1.0=py37h2852a4a_1
  - mistune=0.8.4=py37hfa6e2cd_1000
  - mkl=2019.4=245
  - more-itertools=4.3.0=py37_1000
  - msys2-conda-epoch=20160418=1
  - munch=2.3.2=py_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - networkx=2.3=py_0
  - nodejs=11.14.0=1
  - notebook=5.7.8=py37_1
  - numexpr=2.6.9=py37h6538335_1000
  - numpy=1.16.4=py37hc71023c_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=ha922770_0
  - openssl=1.1.1b=hfa6e2cd_2
  - owslib=0.18.0=py_0
  - packaging=19.0=py_0
  - palettable=3.1.1=py_0
  - pandas=0.24.2=py37he350917_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.0=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=h6538335_1003
  - pickleshare=0.7.5=py37_1000
  - pillow=6.0.0=py37h9a613e6_0
  - pip=19.1.1=py37_0
  - pkginfo=1.5.0.1=py_0
  - pluggy=0.12.0=py_0
  - poppler=0.67.0=heddaa77_6
  - poppler-data=0.4.9=1
  - postgresql=11.3=h06f7779_0
  - proj4=5.2.0=h6538335_1003
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - psycopg2=2.8.3=py37hb32ad35_0
  - py=1.8.0=py_0
  - pycparser=2.19=py37_1
  - pyepsg=0.4.0=py_0
  - pygments=2.4.2=py_0
  - pykdtree=1.3.1=py37h452e1ab_1002
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyproj=1.9.6=py37hfa6e2cd_1002
  - pyqt=5.9.2=py37h6538335_0
  - pyrsistent=0.15.2=py37hfa6e2cd_0
  - pysal=2.0.0=py_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py37_0
  - pytest=4.6.3=py37_0
  - python=3.7.3=hb12ca83_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - pywinpty=0.5.5=py37_1000
  - pyyaml=5.1.1=py37hfa6e2cd_0
  - pyzmq=18.0.1=py37he7828b0_1
  - qt=5.9.7=hc6833c9_1
  - readme_renderer=24.0=py_0
  - requests=2.22.0=py37_0
  - requests-toolbelt=0.9.1=py_0
  - rtree=0.8.3=py37h21ff451_1002
  - scikit-learn=0.21.2=py37h0ff8352_0
  - scipy=1.2.1=py37h29ff71c_0
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py37_0
  - shapely=1.6.4=py37h7d20962_1005
  - sip=4.19.8=py37h6538335_1000
  - six=1.12.0=py37_1000
  - snowballstemmer=1.2.1=py_1
  - soupsieve=1.9.2=py37_0
  - sphinx=2.1.2=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.1=py_0
  - sqlite=3.28.0=hfa6e2cd_0
  - statsmodels=0.10.0=py37hfa6e2cd_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hfa6e2cd_1002
  - toolz=0.9.0=py_1
  - tornado=6.0.3=py37hfa6e2cd_0
  - tqdm=4.32.2=py_0
  - traitlets=4.3.2=py37_1000
  - traittypes=0.2.1=py_1
  - twine=1.13.0=py_1
  - urllib3=1.24.3=py37_0
  - vc=14.1=h0510ff6_4
  - vincent=0.4.4=py_1
  - vs2015_runtime=14.15.26706=h3a45250_4
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.4.2=py37_1000
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_1002
  - winpty=0.4.3=4
  - xarray=0.12.1=py_0
  - xerces-c=3.2.2=h6538335_1001
  - xlrd=1.2.0=py_0
  - xlwt=1.3.0=py_1
  - xz=5.2.4=h2fa13f4_1001
  - yaml=0.1.7=hfa6e2cd_1001
  - zeromq=4.3.1=he025d50_1000
  - zipp=0.5.1=py_0
  - zlib=1.2.11=h2fa13f4_1004
  - zstd=1.4.0=hd8a0e53_0
  - pip:
    - python-igraph==0.7.1.post6
prefix: G:\Anaconda\envs\ox

