name: ox
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - alabaster=0.7.12=py_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.3.0=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py_0
  - beautifulsoup4=4.8.2=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - blosc=1.17.0=h6538335_1
  - bokeh=1.4.0=py37_0
  - boost-cpp=1.70.0=h6a4c333_2
  - bottleneck=1.3.1=py37hc8d92b1_0
  - branca=0.3.1=py_0
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cartopy=0.17.0=py37hde43876_1009
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37hb32ad35_0
  - cfitsio=3.470=hfa6e2cd_2
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cmarkgfm=0.4.2=py37hfa6e2cd_2
  - colorama=0.4.3=py_0
  - coverage=5.0.2=py37hfa6e2cd_0
  - coveralls=1.10.0=py_0
  - cryptography=2.8=py37hb32ad35_1
  - curl=7.65.3=h4496350_0
  - cycler=0.10.0=py_2
  - cython=0.29.14=py37h6538335_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - deprecated=1.2.7=py_0
  - descartes=1.1.0=py_4
  - dill=0.3.1.1=py37_0
  - docopt=0.6.2=py_1
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he025d50_1004
  - fiona=1.8.13=py37hb7fdc2d_0
  - folium=0.10.1=py_0
  - freetype=2.10.0=h563cfd7_1
  - freexl=1.0.5=hd288d7e_1002
  - future=0.18.2=py37_0
  - gdal=3.0.2=py37h2fee047_5
  - geographiclib=1.50=py_0
  - geopandas=0.6.2=py_0
  - geopy=1.20.0=py_0
  - geos=3.8.0=he025d50_0
  - geotiff=1.5.1=h765a46f_7
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.58.3=py37hc0c2ac7_1002
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.5=nompi_ha405e13_1104
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.8=py37_1000
  - imagesize=1.2.0=py_0
  - importlib_metadata=1.3.0=py37_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.11.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.2=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=hfa6e2cd_1001
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.3=py37_1
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.2.4=py_0
  - jupyterlab_server=1.0.6=py_0
  - kealib=1.4.10=hf7dc31f_1005
  - keyring=21.0.0=py37_0
  - kiwisolver=1.1.0=py37he980bc4_0
  - krb5=1.16.4=hdd46e55_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.1=default_hf44288c_0
  - libcurl=7.65.3=h4496350_0
  - libffi=3.2.1=h6538335_1006
  - libgdal=3.0.2=hafedd80_5
  - libiconv=1.15=hfa6e2cd_1005
  - libkml=1.3.0=h4ece8bf_1010
  - liblapack=3.8.0=14_mkl
  - libnetcdf=4.7.1=nompi_he2c6080_102
  - libpng=1.6.37=h7602738_0
  - libpq=11.5=hb0bdaea_2
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialindex=1.9.3=he025d50_1
  - libspatialite=4.3.0a=he9c6e69_1033
  - libssh2=1.8.2=h642c060_2
  - libtiff=4.1.0=h21b02b4_3
  - libwebp=1.0.2=hfa6e2cd_5
  - libxml2=2.9.10=h9ce36c8_0
  - lz4-c=1.8.3=he025d50_1001
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - markupsafe=1.1.1=py37hfa6e2cd_0
  - matplotlib=3.1.2=py37_1
  - matplotlib-base=3.1.2=py37h2981e6d_1
  - mistune=0.8.4=py37hfa6e2cd_1000
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hfa6e2cd_0
  - mock=3.0.5=py37_0
  - more-itertools=8.0.2=py_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.3=py_0
  - networkx=2.4=py_0
  - nodejs=13.0.0=1
  - notebook=6.0.1=py37_0
  - numexpr=2.7.1=py37h6538335_0
  - numpy=1.17.3=py37hc71023c_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1d=hfa6e2cd_0
  - osmnet=0.1.5=py_3
  - owslib=0.19.0=py_2
  - packaging=20.0=py_0
  - palettable=3.3.0=py_0
  - pandana=0.4.4=py37he350917_0
  - pandas=0.25.3=py37he350917_0
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.2=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=h6538335_0
  - pickleshare=0.7.5=py37_1000
  - pillow=7.0.0=py37h9ea1dd6_0
  - pip=19.3.1=py37_0
  - pkginfo=1.5.0.1=py_0
  - pluggy=0.13.0=py37_0
  - poppler=0.67.0=h1707e21_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=h06f7779_2
  - proj=6.2.1=ha7a8c7b_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - psycopg2=2.8.4=py37hb32ad35_0
  - py=1.8.1=py_0
  - pycparser=2.19=py37_1
  - pyepsg=0.4.0=py_0
  - pygments=2.5.2=py_0
  - pykdtree=1.3.1=py37hc8d92b1_1002
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyproj=2.4.2.post1=py37h9716dcf_0
  - pyqt=5.12.3=py37h6538335_1
  - pyreadline=2.1=py37_1001
  - pyrsistent=0.15.6=py37hfa6e2cd_0
  - pysal=2.1.0=py_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37_0
  - pytables=3.6.1=py37h26f9782_0
  - pytest=5.3.2=py37_0
  - python=3.7.6=h5b45d93_1
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywin32=225=py37hfa6e2cd_0
  - pywin32-ctypes=0.2.0=py37_1000
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.3=py37hfa6e2cd_0
  - pyzmq=18.1.1=py37h16f9016_0
  - qt=5.12.5=h7ef1ec2_0
  - rasterio=1.1.2=py37h2617b1b_0
  - readme_renderer=24.0=py_0
  - requests=2.22.0=py37_1
  - requests-toolbelt=0.9.1=py_0
  - rtree=0.9.3=py37hbf79ddb_0
  - scikit-learn=0.22.1=py37h7208079_0
  - scipy=1.3.1=py37h29ff71c_0
  - seaborn=0.9.0=py_2
  - send2trash=1.5.0=py_0
  - setuptools=44.0.0=py37_0
  - shapely=1.6.4=py37h2130f3d_1007
  - six=1.13.0=py37_0
  - snowballstemmer=2.0.0=py_0
  - snuggs=1.4.7=py_0
  - soupsieve=1.9.4=py37_0
  - sphinx=2.3.1=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sqlite=3.30.1=hfa6e2cd_0
  - statsmodels=0.10.2=py37hc8d92b1_0
  - tbb=2018.0.5=he980bc4_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tiledb=1.7.0=hffbbd95_2
  - tk=8.6.10=hfa6e2cd_0
  - tornado=6.0.3=py37hfa6e2cd_0
  - tqdm=4.41.1=py_0
  - traitlets=4.3.3=py37_0
  - twine=3.1.1=py37_0
  - urbanaccess=0.2.0=py_0
  - urllib3=1.25.7=py37_0
  - vc=14.1=h0510ff6_4
  - vincent=0.4.4=py_1
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_1003
  - winpty=0.4.3=4
  - wrapt=1.11.2=py37hfa6e2cd_0
  - xerces-c=3.2.2=h6538335_1004
  - xlrd=1.2.0=py_0
  - xlwt=1.3.0=py_1
  - xz=5.2.4=h2fa13f4_1001
  - yaml=0.2.2=hfa6e2cd_1
  - zeromq=4.3.2=h6538335_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=hd8a0e53_1
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - python-igraph==0.7.1.post6
prefix: C:\Anaconda\envs\ox

