dist: xenial
language: python
python:
  - 2.7
  - 3.6
  - 3.7

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set show_channel_urls true
  - conda create --name TESTENV --override-channels -c conda-forge python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
  - conda activate TESTENV
  - conda info --all
  - conda list

install:
  - pip install .
  - pip show osmnx

script:
  - coverage run --source osmnx -m pytest --verbose

after_success:
  - coverage report -m
  - coveralls
  