name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=3.0.1=py37_0
  - asn1crypto=0.24.0=py37_1003
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - boost-cpp=1.68.0=h11c811c_1000
  - branca=0.3.1=py_0
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - cairo=1.16.0=ha4e643d_1000
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - conda=4.6.14=py37_0
  - cryptography=2.6.1=py37h72c5cf5_0
  - curl=7.64.1=hf8cf82a_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - descartes=1.1.0=py_3
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=hf484d3e_1002
  - fiona=1.8.6=py37hf242f0b_3
  - folium=0.8.3=py_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - freexl=1.0.5=h14c3975_1002
  - gdal=2.4.1=py37hf242f0b_2
  - geographiclib=1.49=py_0
  - geopandas=0.5.0=py_2
  - geopy=1.19.0=py_0
  - geos=3.7.1=hf484d3e_1000
  - geotiff=1.5.1=he0d578f_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - glib=2.58.3=hf63aee3_1001
  - gmp=6.1.2=hf484d3e_1000
  - gst-plugins-base=1.14.4=hdf3bae2_1001
  - gstreamer=1.14.4=h66beb1c_1001
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py37_1000
  - igraph=0.7.1=h2166141_1005
  - ipykernel=5.1.0=py37h24bf2e0_1002
  - ipython=7.5.0=py37h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - jsonschema=3.0.1=py37_0
  - jupyter_client=5.2.4=py_3
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.35.6=py37_0
  - jupyterlab_server=0.2.0=py_0
  - kealib=1.4.10=h1978553_1003
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=8_openblas
  - libcblas=3.8.0=8_openblas
  - libcurl=7.64.1=hda55be3_0
  - libdap4=3.19.1=hd48c02d_1000
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgdal=2.4.1=h1500935_2
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h328b03d_1009
  - liblapack=3.8.0=8_openblas
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libpng=1.6.37=hed695b0_0
  - libpq=11.2=h4e4e079_1
  - libsodium=1.0.16=h14c3975_1001
  - libspatialindex=1.9.0=he1b5a44_0
  - libspatialite=4.3.0a=h3360108_1027
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h9022e91_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_0
  - mapclassify=2.0.1=py_0
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.0.3=py37_1
  - matplotlib-base=3.0.3=py37h5f35d83_1
  - mistune=0.8.4=py37h14c3975_1000
  - munch=2.3.2=py_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.3=py_0
  - notebook=5.7.8=py37_0
  - numpy=1.16.3=py37he5ce36f_0
  - openblas=0.3.6=h6e990d7_1
  - openjpeg=2.3.1=h58a6597_0
  - openssl=1.1.1b=h14c3975_1
  - osmnx=0.10=py_0
  - pandas=0.24.2=py37hf484d3e_0
  - pandoc=2.7.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.4.0=py_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.1=py37_0
  - pixman=0.34.0=h14c3975_1003
  - poppler=0.67.0=h2ad7f00_6
  - poppler-data=0.4.9=1
  - postgresql=11.2=hbeee2d4_1
  - proj4=6.0.0=h765ec9c_0
  - prometheus_client=0.6.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycairo=1.18.1=py37h438ddbb_0
  - pycosat=0.6.3=py37h14c3975_1001
  - pycparser=2.19=py37_1
  - pygments=2.4.0=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyproj=2.1.3=py37h7bc548f_1
  - pyqt=5.9.2=py37hcca6a23_0
  - pyrsistent=0.15.1=py37h516909a_0
  - pysocks=1.6.8=py37_1002
  - python=3.7.3=h5b0a415_0
  - python-dateutil=2.8.0=py_0
  - python-igraph=0.7.1.post7=py37h516909a_0
  - pytz=2019.1=py_0
  - pyzmq=18.0.1=py37hc4ba49a_1
  - qt=5.9.7=h52cfd70_1
  - readline=7.0=hf8c457e_1001
  - requests=2.21.0=py37_1000
  - rtree=0.8.3=py37h666c49c_1002
  - ruamel_yaml=0.15.71=py37h14c3975_1000
  - scipy=1.2.1=py37h09a28d5_1
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py37_0
  - shapely=1.6.4=py37h2afed24_1004
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - sqlite=3.26.0=h67949de_1001
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=h84994c4_1001
  - toolz=0.9.0=py_1
  - tornado=6.0.2=py37h516909a_0
  - traitlets=4.3.2=py37_1000
  - tzcode=2018g=h14c3975_1001
  - urllib3=1.24.2=py37_0
  - vincent=0.4.4=py_1
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.1=py37_0
  - xerces-c=3.2.2=hac72e42_1001
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h516909a_1004
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.1=hf484d3e_1000
  - zlib=1.2.11=h14c3975_1004
  - zstd=1.3.3=1
prefix: /opt/conda

