name: base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - access=1.1.8=pyhd8ed1ab_0
  - affine=2.4.0=pyhd8ed1ab_0
  - alabaster=0.7.13=pyhd8ed1ab_0
  - alembic=1.11.1=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311hd4cff14_3
  - arpack=3.7.0=hdefa2d7_2
  - arrow=1.2.3=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-lru=2.0.3=pyhd8ed1ab_0
  - async_generator=1.10=py_0
  - attrs=23.1.0=pyh71513ae_1
  - autopep8=2.0.2=pyhd8ed1ab_0
  - aws-c-auth=0.7.0=hf8751d9_2
  - aws-c-cal=0.6.0=h93469e0_0
  - aws-c-common=0.8.23=hd590300_0
  - aws-c-compression=0.2.17=h862ab75_1
  - aws-c-event-stream=0.3.1=h9599702_1
  - aws-c-http=0.7.11=hbe98c3e_0
  - aws-c-io=0.13.28=h3870b5a_0
  - aws-c-mqtt=0.8.14=h2e270ba_2
  - aws-c-s3=0.3.13=heb0bb06_2
  - aws-c-sdkutils=0.1.11=h862ab75_1
  - aws-checksums=0.1.16=h862ab75_1
  - aws-crt-cpp=0.20.3=he9c0e7f_4
  - aws-sdk-cpp=1.10.57=hbc2ea52_17
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - black=23.7.0=py311h38be061_1
  - bleach=6.0.0=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - blosc=1.21.4=h0f2a231_0
  - bokeh=3.2.1=pyhd8ed1ab_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - boolean.py=4.0=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h6582d0a_3
  - bottleneck=1.3.7=py311hcb2cf0a_0
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py311ha362b79_9
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=hbbf8b49_1016
  - cartopy=0.21.1=py311hd88b842_1
  - certifi=2023.7.22=pyhd8ed1ab_0
  - certipy=0.1.3=py_0
  - cffi=1.15.1=py311h409f033_3
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cfitsio=4.2.0=hd9d235c_0
  - chardet=5.1.0=py311h38be061_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.6=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cmarkgfm=0.8.0=py311hd4cff14_2
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.8=ha2443b9_0
  - coin-or-utils=2.11.9=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - conda=23.7.2=py311h38be061_0
  - conda-build=3.26.0=py311h38be061_1
  - conda-forge-pinning=2023.07.28.13.20.40=hd8ed1ab_0
  - conda-index=0.2.3=pyhd8ed1ab_0
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.8.0=pyhd8ed1ab_0
  - conda-smithy=3.24.1=pyhd8ed1ab_0
  - configurable-http-proxy=4.5.4=he2f69ee_2
  - contextily=1.3.0=pyhd8ed1ab_0
  - contourpy=1.1.0=py311h9547e67_0
  - coverage=7.2.7=py311h459d7ec_0
  - cryptography=41.0.2=py311h63ff55d_0
  - curl=8.2.1=hca28451_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=3.0.0=py311hb755f60_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.7=py311hcafe171_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - descartes=1.1.0=py_4
  - distlib=0.3.7=pyhd8ed1ab_0
  - docutils=0.20.1=py311h38be061_0
  - editables=0.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - esda=2.4.3=pyhd8ed1ab_0
  - exceptiongroup=1.1.2=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - filelock=3.12.2=pyhd8ed1ab_0
  - fiona=1.9.4=py311hbac4ec9_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - fmt=9.1.0=h924138e_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.41.1=py311h459d7ec_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hca18f0e_1
  - freexl=1.0.6=h166bdaf_1
  - furo=2023.7.26=pyhd8ed1ab_0
  - gdal=3.7.0=py311h1caf18b_3
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.13.2=pyhd8ed1ab_1
  - geopandas-base=0.13.2=pyha770c72_1
  - geopy=2.3.0=pyhd8ed1ab_0
  - geos=3.11.2=hcb278e6_0
  - geotiff=1.7.1=h22adcc9_11
  - gettext=0.21.1=h27087fc_0
  - giddy=2.3.4=pyhd8ed1ab_0
  - giflib=5.2.1=h0b41bf4_3
  - git=2.41.0=pl5321h86e50cf_0
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.32=pyhd8ed1ab_0
  - glob2=0.7=py_0
  - glpk=5.0=h445213a_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py311h6a5fa03_1
  - greenlet=2.0.2=py311hb755f60_1
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hatch=1.7.0=pyhd8ed1ab_0
  - hatchling=1.18.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.1=nompi_h4f84152_100
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=0.17.3=pyhd8ed1ab_0
  - httpx=0.24.1=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - hyperlink=21.0.0=pyhd3deb0d_0
  - icu=72.1=hcb278e6_0
  - identify=2.5.26=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.0=pyhd8ed1ab_1
  - inequality=1.0.0=py_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.25.0=pyh71e2992_0
  - ipython=8.14.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.7=pyhd8ed1ab_0
  - isodate=0.6.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.0=pyhd8ed1ab_1
  - json-c=0.16=hc379101_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.18.4=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.18.4=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyh5bfe37b_1
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h38be061_0
  - jupyter_events=0.6.3=pyhd8ed1ab_1
  - jupyter_server=2.7.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyter_telemetry=0.1.0=pyhd8ed1ab_1
  - jupyterhub=4.0.1=pyh2a2186d_0
  - jupyterhub-base=4.0.1=pyh2a2186d_0
  - jupyterlab=4.0.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.8=pyhd8ed1ab_0
  - kealib=1.5.1=h3e6883b_4
  - keyring=24.2.0=py311h38be061_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py311h4dd048b_1
  - krb5=1.21.1=h659d440_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libarchive=3.6.2=h039dbb9_1
  - libblas=3.9.0=17_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcblas=3.9.0=17_linux64_openblas
  - libcurl=8.2.1=hca28451_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgdal=3.7.0=h4a547c6_3
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.4=hebfc3b9_0
  - libgomp=13.1.0=he5830b7_0
  - libhwloc=2.9.2=nocuda_h7313eea_1008
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - libkml=1.3.0=h37653c0_1015
  - liblapack=3.9.0=17_linux64_openblas
  - liblapacke=3.9.0=17_linux64_openblas
  - liblief=0.12.3=h27087fc_0
  - libllvm14=14.0.6=hcd5def8_4
  - libmamba=1.4.9=h658169a_0
  - libmambapy=1.4.9=py311h527f279_0
  - libnetcdf=4.9.2=nompi_h7e745eb_109
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hfc447b1_2
  - libpysal=4.7.0=pyhd8ed1ab_0
  - librttopo=1.1.0=h0d5128d_13
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.24=hfc55251_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=hca56755_27
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.1=h8b53f26_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.44.2=hd590300_1
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.4=h0d562d8_0
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=hd590300_5
  - license-expression=30.1.1=pyhd8ed1ab_0
  - llvmlite=0.40.1=py311ha6695c7_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mako=1.2.4=pyhd8ed1ab_0
  - mamba=1.4.9=py311h3072747_0
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311h459d7ec_0
  - matplotlib-base=3.7.2=py311h54ef318_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - metis=5.1.1=h59595ed_0
  - mgwr=2.1.2=py_0
  - mistune=3.0.0=pyhd8ed1ab_0
  - momepy=0.6.0=pyhd8ed1ab_1
  - more-itertools=10.0.0=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msrest=0.6.21=pyh44b312d_0
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.7.3=pyhd8ed1ab_0
  - nbconvert-core=7.7.3=pyhd8ed1ab_0
  - nbconvert-pandoc=7.7.3=pyhd8ed1ab_0
  - nbdime=3.2.1=pyhd8ed1ab_0
  - nbformat=5.9.1=pyhd8ed1ab_0
  - nbqa=1.7.0=pyhd8ed1ab_1
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - nodeenv=1.8.0=pyhd8ed1ab_0
  - nodejs=18.16.1=hf52ce11_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=7.0.0=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numba=0.57.1=py311h96b013e_0
  - numexpr=2.8.4=py311h039bad6_101
  - numpy=1.24.4=py311h64a7726_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.1=hd590300_1
  - osmnx=1.6.0=pyhd8ed1ab_0
  - overrides=7.3.1=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pamela=1.0.0=py_0
  - pandas=2.0.3=py311h320fe9a_1
  - pandoc=3.1.3=h32600fe_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pathspec=0.11.1=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=4_hd590300_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.0=py311h0b84326_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.9.1=pyhd8ed1ab_0
  - pluggy=1.2.0=pyhd8ed1ab_0
  - pointpats=2.3.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.05.0=hd18248d_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.3=h8972f4a_2
  - pre-commit=3.3.3=pyha770c72_0
  - proj=9.2.1=ha643af7_0
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py311h2582759_0
  - psycopg2=2.9.6=py311h68d4568_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.7.0=py311h38be061_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-lief=0.12.3=py311ha362b79_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycosat=0.6.4=py311hd4cff14_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pycryptodome=3.18.0=py311h6601440_0
  - pycurl=7.45.1=py311hae980a4_3
  - pygithub=1.59.0=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py311hd4cff14_2
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pyproj=3.6.0=py311ha169711_1
  - pysal=23.1=pyhd8ed1ab_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.0=pyhd8ed1ab_0
  - pytest-cov=4.1.0=pyhd8ed1ab_0
  - python=3.11.4=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
  - python-igraph=0.10.6=py311h4b1723a_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-libarchive-c=5.0=py311h38be061_1
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py311hd4cff14_5
  - pyzmq=25.1.0=py311h75c88c4_0
  - quantecon=0.5.3=pyhd8ed1ab_0
  - rasterio=1.3.8=py311h41e4db2_0
  - rasterstats=0.19.0=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - readme_renderer=40.0=pyhd8ed1ab_0
  - referencing=0.30.0=pyhd8ed1ab_0
  - reproc=14.2.4=h0b41bf4_0
  - reproc-cpp=14.2.4=hcb278e6_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986=2.0.0=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.4.2=pyhd8ed1ab_0
  - ripgrep=13.0.0=h2f28480_2
  - rocm-smi=5.6.0=h59595ed_1
  - rpds-py=0.9.2=py311h46250e7_0
  - rtree=1.0.1=py311h3bb2b0f_2
  - ruamel.yaml=0.17.32=py311h459d7ec_0
  - ruamel.yaml.clib=0.2.7=py311h2582759_1
  - ruff=0.0.280=py311h7145743_0
  - s2n=1.3.46=h06160fa_0
  - scikit-learn=1.3.0=py311hc009520_0
  - scipy=1.11.1=py311h64a7726_0
  - scrypt=0.8.18=py311h7594263_4
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - secretstorage=3.3.3=py311h38be061_1
  - segregation=2.4.2=pyhd8ed1ab_0
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - shapely=2.0.1=py311h54d622a_1
  - shellingham=1.5.1=pyhd8ed1ab_0
  - simplejson=3.19.1=py311h2582759_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - spaghetti=1.7.4=pyhd8ed1ab_0
  - spglm=1.0.8=py_0
  - sphinx=7.0.1=pyhd8ed1ab_0
  - sphinx-basic-ng=1.0.0b2=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - spint=1.0.7=pyhd8ed1ab_0
  - splot=1.1.5.post1=pyhd8ed1ab_0
  - spopt=0.5.0=pyhd8ed1ab_0
  - spreg=1.3.2=pyhd8ed1ab_0
  - spvcm=0.3.0=py_0
  - sqlalchemy=2.0.19=py311h459d7ec_0
  - sqlite=3.42.0=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py311h1f0f07a_1
  - suitesparse=5.10.1=h9e50725_1
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.10.0=h00ab1b0_0
  - terminado=0.17.1=pyh41d4057_0
  - texttable=1.6.7=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiledb=2.13.2=hd532e3d_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tobler=0.10.1=pyhd8ed1ab_0
  - tokenize-rt=5.1.0=pyhd8ed1ab_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomli-w=1.0.0=pyhd8ed1ab_0
  - tomlkit=0.12.1=pyha770c72_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.2=py311h459d7ec_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - trove-classifiers=2023.7.6=pyhd8ed1ab_0
  - twine=4.0.2=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzcode=2023c=h0b41bf4_0
  - tzdata=2023c=h71feb2d_0
  - ukkonen=1.0.1=py311h4dd048b_3
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - userpath=1.7.0=pyhd8ed1ab_0
  - virtualenv=20.24.2=pyhd8ed1ab_0
  - vsts-python-api=0.1.25=pyhd8ed1ab_1
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.1=pyhd8ed1ab_0
  - wheel=0.41.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.8=pyhd8ed1ab_0
  - wrapt=1.15.0=py311h2582759_0
  - xerces-c=3.2.4=h8d71039_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2023.7.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.7.0=h27087fc_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.19.0=py311haa97af0_2
  - zstd=1.5.2=hfc55251_7
prefix: /opt/conda
