name: ox
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - affine=2.3.0=py_0
  - alabaster=0.7.12=py_0
  - attrs=19.3.0=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py_0
  - beautifulsoup4=4.8.2=py38_0
  - bleach=3.1.3=pyh8c360ce_0
  - blosc=1.17.1=he1b5a44_0
  - bokeh=2.0.0=py38h32f6830_0
  - boost-cpp=1.72.0=h8e57a91_0
  - bottleneck=1.3.2=py38h8790de6_1
  - branca=0.4.0=py_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hcf35c78_1003
  - cartopy=0.17.0=py38h4118a90_1013
  - certifi=2019.11.28=py38h32f6830_1
  - cffi=1.14.0=py38hd463f26_0
  - cfitsio=3.470=hb60a0a2_2
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.1=pyh8c360ce_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cmarkgfm=0.4.2=py38h516909a_2
  - coverage=5.0.4=py38h1e0a361_0
  - coveralls=1.11.1=py_0
  - cryptography=2.8=py38h766eaa4_2
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py_2
  - cython=0.29.15=py38h950e882_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - deprecated=1.2.7=py_0
  - descartes=1.1.0=py_4
  - dill=0.3.1.1=py38h32f6830_1
  - docopt=0.6.2=py_1
  - docutils=0.16=py38h32f6830_1
  - entrypoints=0.3=py38h32f6830_1001
  - expat=2.2.9=he1b5a44_2
  - fiona=1.8.13=py38h900e953_0
  - folium=0.10.1=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.1=he06d7ca_0
  - freexl=1.0.5=h14c3975_1002
  - future=0.18.2=py38h32f6830_1
  - gdal=3.0.4=py38h172510d_2
  - geographiclib=1.50=py_0
  - geopandas=0.7.0=py_1
  - geopy=1.21.0=py_0
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.5.1=hcbe54f9_9
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.58.3=py38h73cb85d_1003
  - gmp=6.2.0=he1b5a44_2
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.5.0=py38h32f6830_1
  - importlib_metadata=1.5.0=1
  - ipykernel=5.2.0=py38h23f93f0_0
  - ipython=7.13.0=py38h32f6830_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.16.0=py38h32f6830_1
  - jeepney=0.4.3=py_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.0=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - jupyterlab=2.0.1=py_0
  - jupyterlab_server=1.0.7=py_0
  - kealib=1.4.12=hec59c27_0
  - keyring=21.1.1=py38h32f6830_1
  - kiwisolver=1.1.0=py38hbf85e49_1
  - krb5=1.16.4=h2fd8d38_0
  - ld_impl_linux-64=2.34=h53a641e_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.68.0=hda55be3_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgdal=3.0.4=hce44138_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1006
  - libkml=1.3.0=hb574062_1011
  - liblapack=3.8.0=16_openblas
  - libllvm9=9.0.1=hc9558a2_0
  - libnetcdf=4.7.3=nompi_h9f9fd6a_101
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libpq=12.2=hae5116b_0
  - libsodium=1.0.17=h516909a_0
  - libspatialindex=1.9.3=he1b5a44_3
  - libspatialite=4.3.0a=heb269f5_1037
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.34.0=h516909a_0
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=9.0.1=hc9558a2_2
  - lz4-c=1.8.3=he1b5a44_1001
  - lzo=2.10=h14c3975_1000
  - markupsafe=1.1.1=py38h1e0a361_1
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py38h2af1d28_0
  - mistune=0.8.4=py38h516909a_1000
  - mock=3.0.5=py38h32f6830_1
  - more-itertools=8.2.0=py_0
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_1
  - nodejs=13.10.1=hf5d1a2b_0
  - notebook=6.0.3=py38_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numexpr=2.7.1=py38hcb8c335_1
  - numpy=1.18.1=py38h8854b6b_1
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1e=h516909a_0
  - osmnet=0.1.5=py_3
  - owslib=0.19.2=py_1
  - packaging=20.1=py_0
  - palettable=3.3.0=py_0
  - pandana=0.4.4=py38hb3f55d8_1
  - pandas=1.0.3=py38hcb8c335_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.2=py_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1001
  - pillow=7.0.0=py38h9776b28_1
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - pkginfo=1.5.0.1=py_0
  - pluggy=0.13.1=py38_0
  - poppler=0.67.0=h14e79db_8
  - poppler-data=0.4.9=1
  - postgresql=12.2=hf1211e9_0
  - proj=6.3.1=hc80f0dc_1
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - psycopg2=2.8.4=py38h72c5cf5_1
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.8.1=py_0
  - pycairo=1.19.1=py38h323dad1_3
  - pycparser=2.20=py_0
  - pyepsg=0.4.0=py_0
  - pygments=2.6.1=py_0
  - pykdtree=1.3.1=py38h8790de6_1003
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.6=py_0
  - pyproj=2.6.0=py38h95a477d_0
  - pyqt=5.12.3=py38hcca6a23_1
  - pyrsistent=0.15.7=py38h1e0a361_1
  - pysal=2.1.0=py_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py38h32f6830_1
  - pytables=3.6.1=py38h9f153d1_1
  - pytest=5.4.1=py38h32f6830_0
  - python=3.8.2=h8356626_5_cpython
  - python-dateutil=2.8.1=py_0
  - python-igraph=0.8.0=py38hb721cf7_1
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pyyaml=5.2=py38h516909a_0
  - pyzmq=19.0.0=py38ha71036d_1
  - qt=5.12.5=hd8c4c69_1
  - rasterio=1.1.3=py38h900e953_0
  - readline=8.0=hf8c457e_0
  - readme_renderer=24.0=py_0
  - requests=2.23.0=pyh8c360ce_2
  - requests-toolbelt=0.9.1=py_0
  - rtree=0.9.4=py38h08f867b_1
  - scikit-learn=0.22.2.post1=py38hcdab131_0
  - scipy=1.4.1=py38h921218d_0
  - seaborn=0.10.0=py_1
  - secretstorage=3.1.2=py38h32f6830_1
  - send2trash=1.5.0=py_0
  - setuptools=46.1.1=py38h32f6830_0
  - shapely=1.7.0=py38hd168ffb_2
  - six=1.14.0=py_1
  - snowballstemmer=2.0.0=py_0
  - snuggs=1.4.7=py_0
  - soupsieve=1.9.4=py38h32f6830_1
  - sphinx=2.4.4=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.30.1=hcee41ef_0
  - statsmodels=0.11.1=py38h1e0a361_1
  - tbb=2018.0.5=h2d50403_0
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - texttable=1.6.2=py_0
  - tiledb=1.7.0=hcde45ca_2
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py38h1e0a361_1
  - tqdm=4.43.0=py_0
  - traitlets=4.3.3=py38h32f6830_1
  - twine=3.1.1=py38_0
  - typing_extensions=3.7.4.1=py38h32f6830_1
  - tzcode=2019a=h516909a_1002
  - urbanaccess=0.2.0=py_1
  - urllib3=1.25.7=py38h32f6830_1
  - vincent=0.4.4=py_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - wrapt=1.12.1=py38h1e0a361_1
  - xerces-c=3.2.2=h8412b87_1004
  - xlrd=1.2.0=py_0
  - xlwt=1.3.0=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h516909a_1002
  - yaml=0.2.2=h516909a_1
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /home/geoff/miniconda3/envs/ox

