name: ox
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - access=1.1.8=pyhd8ed1ab_1
  - affine=2.4.0=pyhd8ed1ab_0
  - alabaster=0.7.13=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - anyio=4.1.0=pyhd8ed1ab_0
  - archspec=0.2.2=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h459d7ec_4
  - arpack=3.8.0=nompi_h0baa96a_101
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.13.1=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - blosc=1.21.5=h0f2a231_0
  - bokeh=3.3.1=pyhd8ed1ab_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - boolean.py=4.0=pyhd8ed1ab_0
  - bottleneck=1.3.7=py311h1f0f07a_1
  - branca=0.7.0=pyhd8ed1ab_1
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py311hb755f60_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.22.1=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - cartopy=0.22.0=py311h320fe9a_1
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py311hb3a22ac_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cfitsio=4.3.0=hbdc6101_0
  - chardet=5.2.0=py311h38be061_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cirun=0.30=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cmarkgfm=0.8.0=py311h459d7ec_3
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.8=ha2443b9_0
  - coin-or-utils=2.11.9=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - conda=23.10.0=py311h38be061_1
  - conda-build=3.27.0=py311h38be061_0
  - conda-forge-pinning=2023.11.30.15.07.46=hd8ed1ab_0
  - conda-index=0.3.0=pyhd8ed1ab_1
  - conda-libmamba-solver=23.11.1=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - conda-smithy=3.30.1=pyhd8ed1ab_0
  - contextily=1.4.0=pyhd8ed1ab_0
  - contourpy=1.2.0=py311h9547e67_0
  - coverage=7.3.2=py311h459d7ec_0
  - cryptography=41.0.5=py311h63ff55d_0
  - curl=8.4.0=hca28451_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cython=3.0.6=py311hb755f60_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.0=py311hb755f60_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - descartes=1.1.0=py_4
  - distlib=0.3.7=pyhd8ed1ab_0
  - docutils=0.20.1=py311h38be061_2
  - editables=0.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - esda=2.5.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - filelock=3.13.1=pyhd8ed1ab_0
  - fiona=1.9.5=py311hbac4ec9_0
  - fmt=10.1.1=h00ab1b0_1
  - folium=0.15.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.45.1=py311h459d7ec_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - freexl=2.0.0=h743c826_0
  - furo=2023.9.10=pyhd8ed1ab_0
  - gdal=3.7.3=py311h815a124_4
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.14.1=pyhd8ed1ab_0
  - geopandas-base=0.14.1=pyha770c72_0
  - geopy=2.4.1=pyhd8ed1ab_0
  - geos=3.12.0=h59595ed_0
  - geotiff=1.7.1=hf074850_14
  - gettext=0.21.1=h27087fc_0
  - giddy=2.3.4=pyhd8ed1ab_1
  - giflib=5.2.1=h0b41bf4_3
  - git=2.42.0=pl5321h86e50cf_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=h59595ed_0
  - gmpy2=2.1.2=py311h6a5fa03_1
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hatch=1.7.0=pyhd8ed1ab_0
  - hatchling=1.18.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.2=nompi_h4f84152_100
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.2=pyhd8ed1ab_0
  - httpx=0.25.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - hyperlink=21.0.0=pyhd3deb0d_0
  - icu=73.2=h59595ed_0
  - identify=2.5.32=pyhd8ed1ab_0
  - idna=3.6=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - inequality=1.0.1=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.18.1=pyh31011fe_1
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - isodate=0.6.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - json-c=0.17=h7ab15ed_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py311h38be061_3
  - jsonschema=4.20.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.11.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.20.0=pyhd8ed1ab_0
  - jupyter-lsp=2.2.1=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyh5bfe37b_1
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py311h38be061_0
  - jupyter_events=0.9.0=pyhd8ed1ab_0
  - jupyter_server=2.11.1=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.25.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - kealib=1.5.2=hcd42e92_1
  - keyring=24.3.0=py311h38be061_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py311h9547e67_1
  - krb5=1.21.2=h659d440_0
  - lcms2=2.15=hb7c19ff_3
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.2=h59595ed_1
  - libarchive=3.7.2=h039dbb9_0
  - libblas=3.9.0=20_linux64_openblas
  - libboost-headers=1.83.0=ha770c72_0
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=20_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgdal=3.7.3=he5b8fdc_4
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_3
  - libgoogle-cloud=2.12.0=h5206363_4
  - libgrpc=1.59.3=hd6c4280_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkml=1.3.0=h01aab08_1018
  - liblapack=3.9.0=20_linux64_openblas
  - liblapacke=3.9.0=20_linux64_openblas
  - liblief=0.12.3=h27087fc_0
  - libllvm14=14.0.6=hcd5def8_4
  - libmamba=1.5.3=had39da4_2
  - libmambapy=1.5.3=py311hf2555c7_2
  - libnetcdf=4.9.2=nompi_h80fb2b6_112
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libpq=16.1=hfc447b1_0
  - libprotobuf=4.24.4=hf27288f_0
  - libpysal=4.9.2=pyhd8ed1ab_1
  - libre2-11=2023.06.02=h7a70373_0
  - librttopo=1.1.0=hb58d41b_14
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.27=hfc55251_0
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.1.0=h090f1da_1
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.6=h232c23b_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - license-expression=30.1.1=pyhd8ed1ab_0
  - llvmlite=0.41.1=py311ha6695c7_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311h459d7ec_1
  - matplotlib-base=3.8.2=py311h54ef318_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - mgwr=2.2.0=pyhd8ed1ab_0
  - minizip=4.0.3=h0ab5242_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - momepy=0.7.0=pyhd8ed1ab_0
  - more-itertools=10.1.0=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msrest=0.6.21=pyh44b312d_0
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.11.0=pyhd8ed1ab_0
  - nbdime=4.0.1=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - nbqa=1.7.1=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nh3=0.2.14=py311h46250e7_1
  - nodeenv=1.8.0=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.95=h1d7d5a4_0
  - numba=0.58.1=py311h96b013e_0
  - numexpr=2.8.7=py311h039bad6_104
  - numpy=1.26.2=py311h64a7726_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.1.4=hd590300_0
  - osmnx=1.8.0=pyhd8ed1ab_0
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.3=py311h320fe9a_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pathspec=0.11.2=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=4_hd590300_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.1.0=py311ha6c5da5_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - pointpats=2.4.0=pyhd8ed1ab_0
  - poppler=23.11.0=h590f24d_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.1=h8972f4a_0
  - pre-commit=3.5.0=pyha770c72_0
  - proj=9.3.0=h1d62c97_2
  - prometheus_client=0.19.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.41=pyha770c72_0
  - psutil=5.9.5=py311h459d7ec_1
  - psycopg2=2.9.7=py311h03dec38_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.7.0=py311h38be061_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-lief=0.12.3=py311ha362b79_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycodestyle=2.11.1=pyhd8ed1ab_0
  - pycosat=0.6.6=py311h459d7ec_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pycryptodome=3.19.0=py311h6601440_1
  - pygithub=2.1.1=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py311h459d7ec_3
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pyproj=3.6.1=py311h1facc83_4
  - pysal=23.7=pyhd8ed1ab_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.3=pyhd8ed1ab_0
  - pytest-cov=4.1.0=pyhd8ed1ab_0
  - python=3.11.6=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.0=pyhd8ed1ab_0
  - python-igraph=0.11.3=py311h535dc8a_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-libarchive-c=5.0=py311h38be061_2
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h459d7ec_1
  - pyzmq=25.1.1=py311h34ded2d_2
  - quantecon=0.5.3=pyhd8ed1ab_0
  - rasterio=1.3.9=py311h40fbdff_0
  - rasterstats=0.19.0=pyhd8ed1ab_0
  - re2=2023.06.02=h2873b5e_0
  - readline=8.2=h8228510_1
  - readme_renderer=42.0=pyhd8ed1ab_0
  - referencing=0.31.1=pyhd8ed1ab_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986=2.0.0=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.7.0=pyhd8ed1ab_0
  - ripgrep=13.0.0=he8a937b_3
  - rpds-py=0.13.2=py311h46250e7_0
  - rtree=1.1.0=py311h3bb2b0f_0
  - ruamel.yaml=0.18.5=py311h459d7ec_0
  - ruamel.yaml.clib=0.2.7=py311h459d7ec_2
  - ruff=0.1.6=py311h7145743_0
  - scikit-learn=1.3.2=py311hc009520_1
  - scipy=1.11.4=py311h64a7726_0
  - scrypt=0.8.20=py311h6965a6d_1
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - secretstorage=3.3.3=py311h38be061_2
  - segregation=2.5=pyhd8ed1ab_1
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shapely=2.0.2=py311he06c224_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - simplejson=3.19.2=py311h459d7ec_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - spaghetti=1.7.4=pyhd8ed1ab_2
  - spglm=1.1.0=pyhd8ed1ab_1
  - sphinx=7.2.6=pyhd8ed1ab_0
  - sphinx-basic-ng=1.0.0b2=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.5=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.4=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.9=pyhd8ed1ab_0
  - spint=1.0.7=pyhd8ed1ab_1
  - splot=1.1.5.post1=pyhd8ed1ab_0
  - spopt=0.5.0=pyhd8ed1ab_2
  - spreg=1.4.2=pyhd8ed1ab_0
  - spvcm=0.3.0=pyhd8ed1ab_1
  - sqlite=3.44.2=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py311h1f0f07a_2
  - sympy=1.12=pypyh9d50eac_103
  - terminado=0.18.0=pyh0d859eb_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiledb=2.16.3=h8c794c1_3
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tobler=0.11.2=pyhd8ed1ab_2
  - tokenize-rt=5.2.0=pyhd8ed1ab_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomli-w=1.0.0=pyhd8ed1ab_0
  - tomlkit=0.12.3=pyha770c72_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.3=py311h459d7ec_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.0=pyhd8ed1ab_0
  - trove-classifiers=2023.11.29=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - twine=4.0.2=pyhd8ed1ab_0
  - typer=0.9.0=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzcode=2023c=h0b41bf4_0
  - tzdata=2023c=h71feb2d_0
  - ukkonen=1.0.1=py311h9547e67_4
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.7=hcb278e6_1
  - urllib3=2.1.0=pyhd8ed1ab_0
  - userpath=1.7.0=pyhd8ed1ab_0
  - virtualenv=20.24.7=pyhd8ed1ab_0
  - vsts-python-api=0.1.25=pyhd8ed1ab_1
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.4=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - wrapt=1.16.0=py311h459d7ec_0
  - xerces-c=3.2.4=hac6953d_3
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py311haa97af0_0
  - zstd=1.5.5=hfc55251_0
prefix: /home/geoff/mambaforge/envs/ox
