name: ox
channels:
  - conda-forge
dependencies:
  - access=1.1.8=pyhd8ed1ab_1
  - affine=2.4.0=pyhd8ed1ab_0
  - alabaster=0.7.13=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - anyio=4.2.0=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - archspec=0.2.2=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311heffc1b2_4
  - arpack=3.8.0=nompi_ha3438d0_101
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - azure-core-cpp=1.10.3=h79b10f0_0
  - azure-storage-blobs-cpp=12.10.0=h6aa02a4_0
  - azure-storage-common-cpp=12.5.0=h607ffeb_2
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - blosc=1.21.5=hc338f07_0
  - bokeh=3.3.2=pyhd8ed1ab_0
  - boltons=23.1.1=pyhd8ed1ab_0
  - boolean.py=4.0=pyhd8ed1ab_0
  - bottleneck=1.3.7=py311hb49d859_1
  - branca=0.7.0=pyhd8ed1ab_1
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py311ha891d26_1
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.24.0=h93a5062_0
  - ca-certificates=2023.11.17=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hd1e100b_0
  - cartopy=0.22.0=py311h6e08293_1
  - cctools=973.0.1=hd1ac623_15
  - cctools_osx-arm64=973.0.1=h2a25c60_15
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py311h4a08483_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cfitsio=4.3.1=h808cd33_0
  - chardet=5.2.0=py311h267d04e_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cirun=0.30=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cmarkgfm=0.8.0=py311heffc1b2_3
  - coin-or-cbc=2.10.10=hfaca913_0
  - coin-or-cgl=0.60.7=hf050ae7_0
  - coin-or-clp=1.17.8=h65c2c7c_0
  - coin-or-osi=0.108.8=h19bcb3e_0
  - coin-or-utils=2.11.9=h12587b1_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - conda=23.11.0=py311h267d04e_1
  - conda-build=3.28.2=py311h267d04e_0
  - conda-forge-pinning=2023.12.31.22.41.20=hd8ed1ab_0
  - conda-index=0.3.0=pyhd8ed1ab_1
  - conda-libmamba-solver=23.12.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - conda-smithy=3.30.2=pyhd8ed1ab_0
  - contextily=1.5.0=pyhd8ed1ab_0
  - contourpy=1.2.0=py311hd03642b_0
  - coverage=7.4.0=py311h05b510d_0
  - cryptography=41.0.7=py311h08c85a6_1
  - curl=8.5.0=h2d989ff_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cython=3.0.7=py311h92babd0_0
  - debugpy=1.8.0=py311ha891d26_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - descartes=1.1.0=py_4
  - distlib=0.3.8=pyhd8ed1ab_0
  - distro=1.8.0=pyhd8ed1ab_0
  - docutils=0.20.1=py311h267d04e_3
  - editables=0.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - esda=2.5.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_1
  - filelock=3.13.1=pyhd8ed1ab_0
  - fiona=1.9.5=py311h1c26527_3
  - fmt=10.1.1=h6aa02a4_1
  - folium=0.15.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.47.0=py311h05b510d_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - freexl=2.0.0=hfbad9fb_0
  - furo=2023.9.10=pyhd8ed1ab_0
  - gdal=3.8.2=py311h4a095a9_1
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.14.1=pyhd8ed1ab_0
  - geopandas-base=0.14.1=pyha770c72_0
  - geopy=2.4.1=pyhd8ed1ab_0
  - geos=3.12.1=h965bd2d_0
  - geotiff=1.7.1=h7bcba05_15
  - gettext=0.21.1=h0186832_0
  - giddy=2.3.4=pyhd8ed1ab_1
  - giflib=5.2.1=h1a8c8d9_3
  - git=2.43.0=pl5321h6e320eb_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glpk=5.0=h6d7a090_0
  - gmp=6.3.0=h965bd2d_0
  - gmpy2=2.1.2=py311h2ba9262_1
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hatch=1.9.1=pyhd8ed1ab_0
  - hatchling=1.21.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.3=nompi_h5bb55e9_100
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.2=pyhd8ed1ab_0
  - httpx=0.26.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - hyperlink=21.0.0=pyhd3deb0d_0
  - icu=73.2=hc8870d7_0
  - identify=2.5.33=pyhd8ed1ab_0
  - idna=3.6=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - inequality=1.0.1=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.28.0=pyh3cd1d5f_0
  - ipython=8.19.0=pyh707e725_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - isodate=0.6.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - json-c=0.17=h40ed0f5_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py311h267d04e_3
  - jsonschema=4.20.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.20.0=pyhd8ed1ab_0
  - jupyter-lsp=2.2.1=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyh5bfe37b_1
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.6.1=py311h267d04e_0
  - jupyter_events=0.9.0=pyhd8ed1ab_0
  - jupyter_server=2.12.1=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.1=pyhd8ed1ab_0
  - jupyterlab=4.0.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.25.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - kealib=1.5.3=h210d843_0
  - keyring=24.3.0=py311h267d04e_0
  - kiwisolver=1.4.5=py311he4fd1f5_1
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.16=ha0e7c42_0
  - ld64=609=h89fa09d_15
  - ld64_osx-arm64=609=hc4dc95b_15
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libaec=1.1.2=h13dd4ca_1
  - libarchive=3.7.2=hcacb583_1
  - libblas=3.9.0=20_osxarm64_openblas
  - libboost-headers=1.84.0=hce30654_0
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=20_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.5.0=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgdal=3.8.2=h7e86f1f_1
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libglib=2.78.3=hb438215_0
  - libgoogle-cloud=2.12.0=hfb399a7_4
  - libgrpc=1.59.3=hbcf6334_0
  - libiconv=1.17=h0d3ecfb_2
  - libjpeg-turbo=3.0.0=hb547adb_1
  - libkml=1.3.0=h1eb4d9f_1018
  - liblapack=3.9.0=20_osxarm64_openblas
  - liblapacke=3.9.0=20_osxarm64_openblas
  - liblief=0.12.3=hb7217d7_0
  - libllvm14=14.0.6=hd1a9a77_4
  - libllvm15=15.0.7=h2621b3d_4
  - libmamba=1.5.6=h90c426b_0
  - libmambapy=1.5.6=py311h26e1311_0
  - libnetcdf=4.9.2=nompi_h291a7c2_113
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libpng=1.6.39=h76d750c_0
  - libpq=16.1=h0f8b458_7
  - libprotobuf=4.24.4=hc9861d8_0
  - libpysal=4.9.2=pyhd8ed1ab_1
  - libre2-11=2023.06.02=h1753957_0
  - librttopo=1.1.0=hc8f776e_15
  - libsodium=1.0.18=h27ca646_1
  - libsolv=0.7.27=h9e231a4_0
  - libspatialindex=1.9.3=hbdafb3b_4
  - libspatialite=5.1.0=h69abc6b_4
  - libsqlite=3.44.2=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtiff=4.6.0=ha8a6c65_2
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.12.3=h0d0cfa8_0
  - libzip=1.10.1=ha0bc3c6_3
  - libzlib=1.2.13=h53f4e23_5
  - license-expression=30.1.1=pyhd8ed1ab_0
  - llvm-openmp=17.0.6=hcd81f8e_0
  - llvmlite=0.41.1=py311hf5d242d_0
  - lz4-c=1.9.4=hb7217d7_0
  - lzo=2.10=h642e427_1000
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311heffc1b2_1
  - matplotlib-base=3.8.2=py311hfdba5f6_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - menuinst=2.0.1=py311h267d04e_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - mgwr=2.2.0=pyhd8ed1ab_0
  - minizip=4.0.4=hc35e051_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - momepy=0.7.0=pyhd8ed1ab_0
  - more-itertools=10.1.0=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.1=h9546428_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msrest=0.6.21=pyh44b312d_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.14.0=pyhd8ed1ab_0
  - nbdime=4.0.1=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - nbqa=1.7.1=pyhd8ed1ab_0
  - ncurses=6.4=h463b476_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nh3=0.2.15=py311h94f323b_0
  - nodeenv=1.8.0=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=hb7217d7_0
  - nss=3.96=h5ce2875_0
  - numba=0.58.1=py311h9ec4793_0
  - numexpr=2.8.8=py311hfbe21a1_0
  - numpy=1.26.2=py311h6d074dd_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=h4c1507b_3
  - openssl=3.2.0=h0d3ecfb_1
  - osmnx=1.8.1=pyhd8ed1ab_0
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.4=py311h6e08293_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patch=2.7.6=h27ca646_1002
  - pathspec=0.12.1=pyhd8ed1ab_0
  - patsy=0.5.5=pyhd8ed1ab_0
  - pcre2=10.42=h26f9a81_0
  - perl=5.32.1=7_h4614cfb_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.1.0=py311hb9c5795_0
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.42.2=h13dd4ca_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - pointpats=2.4.0=pyhd8ed1ab_0
  - poppler=23.12.0=hcdd998b_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.1=h1d0603d_7
  - pre-commit=3.6.0=pyha770c72_0
  - proj=9.3.1=h93d94ba_0
  - prometheus_client=0.19.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.7=py311h05b510d_0
  - psycopg2=2.9.9=py311h589e011_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.7.0=py311h267d04e_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-lief=0.12.3=py311ha397e9f_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycodestyle=2.11.1=pyhd8ed1ab_0
  - pycosat=0.6.6=py311heffc1b2_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pycryptodome=3.19.1=py311h7939e9c_0
  - pygithub=2.1.1=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py311heffc1b2_3
  - pyobjc-core=10.1=py311h665608e_0
  - pyobjc-framework-cocoa=10.1=py311h665608e_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproj=3.6.1=py311h9a031f7_5
  - pysal=23.7=pyhd8ed1ab_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.4=pyhd8ed1ab_0
  - pytest-cov=4.1.0=pyhd8ed1ab_0
  - python=3.11.7=hdf0ec26_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-igraph=0.11.3=py311h5293b00_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-libarchive-c=5.0=py311h267d04e_2
  - python-tzdata=2023.4=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311heffc1b2_1
  - pyzmq=25.1.2=py311h6727e71_0
  - quantecon=0.5.3=pyhd8ed1ab_0
  - rasterio=1.3.9=py311h31af29f_2
  - rasterstats=0.19.0=pyhd8ed1ab_0
  - re2=2023.06.02=h6135d0a_0
  - readline=8.2=h92ec313_1
  - readme_renderer=42.0=pyhd8ed1ab_0
  - referencing=0.32.0=pyhd8ed1ab_0
  - reproc=14.2.4.post0=h93a5062_1
  - reproc-cpp=14.2.4.post0=h965bd2d_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986=2.0.0=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.7.0=pyhd8ed1ab_0
  - ripgrep=14.0.3=h5ef7bb8_1
  - rpds-py=0.16.2=py311h94f323b_0
  - rtree=1.1.0=py311hd698ff7_0
  - ruamel.yaml=0.18.5=py311h05b510d_0
  - ruamel.yaml.clib=0.2.7=py311heffc1b2_2
  - ruff=0.1.9=py311h8c97afb_0
  - scikit-learn=1.3.2=py311ha25ca4d_2
  - scipy=1.11.4=py311h2b215a9_0
  - scrypt=0.8.20=py311h36e034f_1
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - segregation=2.5=pyhd8ed1ab_1
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shapely=2.0.2=py311h0815064_1
  - shellingham=1.5.4=pyhd8ed1ab_0
  - sigtool=0.1.3=h44b9a77_0
  - simplejson=3.19.2=py311h05b510d_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h17c5cce_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - spaghetti=1.7.4=pyhd8ed1ab_2
  - spglm=1.1.0=pyhd8ed1ab_1
  - sphinx=7.2.6=pyhd8ed1ab_0
  - sphinx-basic-ng=1.0.0b2=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.5=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.4=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.9=pyhd8ed1ab_0
  - spint=1.0.7=pyhd8ed1ab_1
  - splot=1.1.5.post1=pyhd8ed1ab_0
  - spopt=0.6.0=pyhd8ed1ab_0
  - spreg=1.4.2=pyhd8ed1ab_0
  - spvcm=0.3.0=pyhd8ed1ab_1
  - sqlite=3.44.2=hf2abe2d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py311h9ea6feb_0
  - sympy=1.12=pypyh9d50eac_103
  - tapi=1100.0.11=he4954df_0
  - terminado=0.18.0=pyh31c8845_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiledb=2.19.0=h567544c_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tobler=0.11.2=pyhd8ed1ab_2
  - tokenize-rt=5.2.0=pyhd8ed1ab_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomli-w=1.0.0=pyhd8ed1ab_0
  - tomlkit=0.12.3=pyha770c72_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.3=py311heffc1b2_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.0=pyhd8ed1ab_0
  - trove-classifiers=2023.11.29=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - twine=4.0.2=pyhd8ed1ab_0
  - typer=0.9.0=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzcode=2023d=h93a5062_0
  - tzdata=2023d=h0c530f3_0
  - ukkonen=1.0.1=py311he4fd1f5_4
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.7=hb7217d7_1
  - urllib3=2.1.0=pyhd8ed1ab_0
  - userpath=1.7.0=pyhd8ed1ab_0
  - virtualenv=20.25.0=pyhd8ed1ab_0
  - vsts-python-api=0.1.25=pyhd8ed1ab_1
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - wrapt=1.16.0=py311h05b510d_0
  - xerces-c=3.2.5=hf393695_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yaml-cpp=0.8.0=h13dd4ca_0
  - zeromq=4.3.5=h965bd2d_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstandard=0.22.0=py311h67b91a1_0
  - zstd=1.5.5=h4f39d0f_0
prefix: /Users/geoff/mambaforge/envs/ox
