name: ox
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - access=1.1.8=pyhd8ed1ab_1
  - affine=2.4.0=pyhd8ed1ab_0
  - alabaster=0.7.16=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - archspec=0.2.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h98912ed_4
  - arpack=3.8.0=nompi_h0baa96a_101
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - autopep8=2.1.0=pyhd8ed1ab_0
  - aws-c-auth=0.7.18=he0b1f16_0
  - aws-c-cal=0.6.11=heb1d5e4_0
  - aws-c-common=0.9.15=hd590300_0
  - aws-c-compression=0.2.18=hce8ee76_3
  - aws-c-event-stream=0.4.2=h01f5eca_8
  - aws-c-http=0.8.1=hdb68c23_10
  - aws-c-io=0.14.7=hbfbeace_6
  - aws-c-mqtt=0.10.4=h50844eb_0
  - aws-c-s3=0.5.7=h6be9164_2
  - aws-c-sdkutils=0.1.15=hce8ee76_3
  - aws-checksums=0.1.18=hce8ee76_3
  - aws-crt-cpp=0.26.8=h2150271_2
  - aws-sdk-cpp=1.11.267=hddb5a97_7
  - azure-core-cpp=1.11.1=h91d86a7_1
  - azure-identity-cpp=1.6.0=hf1915f5_1
  - azure-storage-blobs-cpp=12.10.0=h00ab1b0_1
  - azure-storage-common-cpp=12.5.0=h94269e2_4
  - babel=2.14.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.strenum=1.2.8=pyhd8ed1ab_0
  - backports.tarfile=1.0.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.8.1=pyhd8ed1ab_0
  - blosc=1.21.5=hc2324a3_1
  - boltons=24.0.0=pyhd8ed1ab_0
  - boolean.py=4.0=pyhd8ed1ab_0
  - bottleneck=1.3.8=py312hc7c0aa3_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py312h30efb56_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - cartopy=0.23.0=py312hfb8ada1_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py312hf06ca03_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cfitsio=4.4.0=hbdc6101_1
  - chardet=5.2.0=py312h7900ff3_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cirun=0.30=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cmarkgfm=0.8.0=py312h98912ed_3
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.10=haf5fa05_0
  - coin-or-utils=2.11.11=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=24.3.0=py312h7900ff3_0
  - conda-build=24.3.0=py312h7900ff3_1
  - conda-forge-pinning=2024.05.02.11.25.06=hd8ed1ab_0
  - conda-index=0.4.0=pyhd8ed1ab_0
  - conda-libmamba-solver=24.1.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - conda-smithy=3.35.0=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h8572e83_0
  - coverage=7.5.0=py312h9a8786e_0
  - cryptography=42.0.5=py312h241aef2_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.1=py312h30efb56_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - descartes=1.1.0=py_4
  - distlib=0.3.8=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_0
  - editables=0.5=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - esda=2.5.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - filelock=3.14.0=pyhd8ed1ab_0
  - fiona=1.9.6=py312h66d9856_0
  - fmt=10.2.1=h00ab1b0_0
  - folium=0.16.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py312h98912ed_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - freexl=2.0.0=h743c826_0
  - furo=2024.4.27=pyhd8ed1ab_0
  - gdal=3.8.5=py312hca78659_2
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geos=3.12.1=h59595ed_0
  - geotiff=1.7.1=h6cf1f90_16
  - giddy=2.3.5=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - git=2.45.0=pl5321hef9f9f3_1
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=h59595ed_1
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hatch=1.10.0=pyhd8ed1ab_0
  - hatchling=1.24.2=pyhd8ed1ab_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h4f84152_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - hyperlink=21.0.0=pyhd3deb0d_0
  - icu=73.2=h59595ed_0
  - identify=2.5.36=pyhd8ed1ab_0
  - idna=3.7=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - inequality=1.0.1=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - ipywidgets=8.1.2=pyhd8ed1ab_0
  - isodate=0.6.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_1
  - jaraco.context=5.3.0=pyhd8ed1ab_1
  - jaraco.functools=4.0.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json-c=0.17=h7ab15ed_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py312h7900ff3_3
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyh5bfe37b_1
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h7900ff3_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - kealib=1.5.3=h2f55d51_0
  - keyring=25.2.0=pyha804496_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py312h8572e83_1
  - krb5=1.21.2=h659d440_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.2=h2aa1ff5_1
  - libblas=3.9.0=22_linux64_openblas
  - libboost-headers=1.84.0=ha770c72_2
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=22_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.7.1=hca28451_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_6
  - libgdal=3.8.5=hf9625ee_2
  - libgfortran-ng=13.2.0=h69a702a_6
  - libgfortran5=13.2.0=h43f5ff8_6
  - libglib=2.80.0=hf2295e7_6
  - libgomp=13.2.0=h77fa898_6
  - libgoogle-cloud=2.23.0=h9be4e54_1
  - libgoogle-cloud-storage=2.23.0=hc7a4891_1
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkml=1.3.0=h01aab08_1018
  - liblapack=3.9.0=22_linux64_openblas
  - liblapacke=3.9.0=22_linux64_openblas
  - liblief=0.14.1=hac33072_1
  - libllvm14=14.0.6=hcd5def8_4
  - libmamba=1.5.8=had39da4_0
  - libmambapy=1.5.8=py312hd9e9ff6_0
  - libnetcdf=4.9.2=nompi_h9612171_113
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.2=h33b98f1_1
  - libprotobuf=4.25.3=h08a7969_0
  - libpysal=4.10=pyhd8ed1ab_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - librttopo=1.1.0=h8917695_15
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.29=ha6fb4c9_0
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.1.0=h6f065fc_5
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_6
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_2
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - license-expression=30.1.1=pyhd8ed1ab_0
  - llvmlite=0.42.0=py312hb06c811_1
  - lxml=5.2.1=py312hb90d8a5_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312h98912ed_0
  - matplotlib-base=3.8.4=py312he5832f3_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - menuinst=2.0.2=py312h7900ff3_0
  - mgwr=2.2.1=pyhd8ed1ab_0
  - minizip=4.0.5=h0ab5242_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - momepy=0.7.0=pyhd8ed1ab_0
  - more-itertools=10.2.0=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msrest=0.6.21=pyh44b312d_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=1.10.0=py312h9a8786e_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_0
  - nbdime=4.0.1=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nbqa=1.8.5=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - nh3=0.2.17=py312h4b3b743_0
  - nodeenv=1.8.0=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.98=h1d7d5a4_0
  - numba=0.59.1=py312hacefee8_0
  - numexpr=2.9.0=py312hed3a10b_100
  - numpy=1.26.4=py312heda63a1_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.0=hd590300_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py312hfb8ada1_0
  - pandas-stubs=2.2.1.240316=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py312hdcec9eb_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkginfo=1.10.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pointpats=2.4.0=pyhd8ed1ab_0
  - poppler=24.04.0=hb6cd0d7_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.2=h82ecc9d_1
  - pre-commit=3.7.0=pyha770c72_0
  - proj=9.4.0=h1d62c97_1
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py312h98912ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.8.0=py312h7900ff3_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-lief=0.14.1=py312h7070661_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycodestyle=2.11.1=pyhd8ed1ab_0
  - pycosat=0.6.6=py312h98912ed_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pycryptodome=3.20.0=py312h8666cd8_0
  - pygithub=2.3.0=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py312h98912ed_3
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyproj=3.6.1=py312hb591178_6
  - pysal=23.7=pyhd8ed1ab_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.2.0=pyhd8ed1ab_0
  - pytest-cov=5.0.0=pyhd8ed1ab_0
  - python=3.12.3=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-igraph=0.11.4=py312h7e4364d_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-libarchive-c=5.1=py312h7900ff3_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - pyzmq=26.0.2=py312h8fd38d8_0
  - quantecon=0.7.2=pyhd8ed1ab_0
  - rasterio=1.3.10=py312h061f55c_0
  - rasterstats=0.19.0=pyhd8ed1ab_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - readme_renderer=42.0=pyhd8ed1ab_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986=2.0.0=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.7.1=pyhd8ed1ab_0
  - ripgrep=14.1.0=he8a937b_0
  - rpds-py=0.18.0=py312h4b3b743_0
  - rtree=1.2.0=py312hb0aae1a_0
  - ruamel.yaml=0.18.6=py312h98912ed_0
  - ruamel.yaml.clib=0.2.8=py312h98912ed_0
  - ruff=0.4.2=py312h5715c7c_0
  - s2n=1.4.12=h06160fa_0
  - scikit-learn=1.4.2=py312h394d371_0
  - scipy=1.13.0=py312heda63a1_0
  - scrypt=0.8.24=py312ha7221cd_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - secretstorage=3.3.3=py312h7900ff3_2
  - segregation=2.5=pyhd8ed1ab_1
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - shapely=2.0.4=py312h9e6bd2c_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - simplejson=3.19.2=py312h98912ed_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.0=hdb0a2a9_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - spaghetti=1.7.5.post1=pyhd8ed1ab_0
  - spdlog=1.13.0=hd2e6256_0
  - spglm=1.1.0=pyhd8ed1ab_1
  - sphinx=7.3.7=pyhd8ed1ab_0
  - sphinx-autodoc-typehints=2.1.0=pyhd8ed1ab_0
  - sphinx-basic-ng=1.0.0b2=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=1.0.8=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.5=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - spint=1.0.7=pyhd8ed1ab_1
  - splot=1.1.5.post1=pyhd8ed1ab_0
  - spopt=0.6.0=pyhd8ed1ab_0
  - spreg=1.4.2=pyhd8ed1ab_0
  - spvcm=0.3.0=pyhd8ed1ab_1
  - sqlite=3.45.3=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py312hc7c0aa3_0
  - sympy=1.12=pyh04b8f61_3
  - terminado=0.18.1=pyh0d859eb_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiledb=2.22.0=h27f064a_3
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tobler=0.11.2=pyhd8ed1ab_2
  - tokenize-rt=5.2.0=pyhd8ed1ab_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomli-w=1.0.0=pyhd8ed1ab_0
  - tomlkit=0.12.4=pyha770c72_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py312h98912ed_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trove-classifiers=2024.4.10=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - twine=5.0.0=pyhd8ed1ab_0
  - typeguard=4.2.1=pyhd8ed1ab_0
  - typer=0.12.3=pyhd8ed1ab_0
  - typer-slim=0.12.3=pyhd8ed1ab_0
  - typer-slim-standard=0.12.3=hd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - types-pytz=2024.1.0.20240417=pyhd8ed1ab_0
  - types-requests=2.31.0.20240406=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzcode=2024a=h3f72095_0
  - tzdata=2024a=h0c530f3_0
  - ukkonen=1.0.1=py312h8572e83_4
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.7=h59595ed_1
  - urllib3=2.2.1=pyhd8ed1ab_0
  - userpath=1.7.0=pyhd8ed1ab_0
  - uv=0.1.39=h0ea3d13_0
  - virtualenv=20.26.1=pyhd8ed1ab_0
  - vsts-python-api=0.1.25=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - wrapt=1.16.0=py312h98912ed_0
  - xerces-c=3.2.5=hac6953d_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2024.4.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - zeromq=4.3.5=h75354e8_3
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py312hd58854c_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - osmnx==2.0.0b0
prefix: /home/geoff/mambaforge/envs/ox
