# This workflow runs the test suite using the minimum supported dependency
# versions.
name: Test minimum dependencies

on:
  schedule:
    - cron: "20 4 * * 1" # every monday at 04:20 UTC
  workflow_dispatch:

jobs:
  test_minimum_deps:
    if: ${{ github.repository == 'gboeing/osmnx' }}
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create environment with minimum dependency versions
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          environment-file: ./environments/tests/env-test-minimum-deps.yml
          post-cleanup: none

      - name: Install OSMnx
        run: |
          python -m pip install -e .
          python -m pip check
          micromamba list
          python -m pip show osmnx

      - name: Test code
        run: pytest --verbose --maxfail=1
